# 基础镜像
FROM nacos/nacos-server:v2.4.2
# author
MAINTAINER ruoyi

# 复制conf文件到路径
COPY ./conf/application.properties /home/nacos/conf/application.properties

# 从 plugins 目录复制人大金仓数据源插件与 JDBC 驱动
COPY ./plugins/ /home/nacos/plugins/
