/**
 * MySQL SQL -> Kingbase V8 (PostgreSQL compatible) 转换脚本
 * 处理 RuoYi-Cloud 初始化 SQL 中常见的 MySQL 特有语法
 */
const fs = require('fs');
const path = require('path');

function stripBackticks(sql) {
    return sql.replace(/`/g, '"');
}

function convertColumnType(type) {
    return type
        .replace(/\bbigint\s*unsigned\b/gi, 'bigint')
        .replace(/\bbigint\(\d+\)/gi, 'bigint')
        .replace(/\bint\s*unsigned\b/gi, 'int')
        .replace(/\bint\(\d+\)/gi, 'int')
        .replace(/\bsmallint\(\d+\)/gi, 'smallint')
        .replace(/\btinyint\(\d+\)/gi, 'smallint')
        .replace(/\btinyint\b/gi, 'smallint')
        .replace(/\bdatetime\b/gi, 'timestamp')
        .replace(/\blongtext\b/gi, 'text')
        .replace(/\blongblob\b/gi, 'bytea')
        .replace(/\bblob\b/gi, 'bytea');
}

function convertCreateTable(sql) {
    return sql.replace(
        /CREATE\s+TABLE\s+(?:IF\s+NOT\s+EXISTS\s+)?([`"]?\w+[`"]?)\s*\((.*?)\)\s*(?:ENGINE\s*=\s*\w+)?(?:\s*AUTO_INCREMENT\s*=\s*\d+)?(?:\s*DEFAULT\s+CHARSET\s*=\s*[\w\-]+)?(?:\s*COLLATE\s*=\s*[\w\-]+)?(?:\s*COMMENT\s*=\s*'([^']*)')?\s*;/gsi,
        (match, tableNameRaw, body, tableComment) => {
            const tableName = tableNameRaw.replace(/[`"]/g, '');
            const indexes = [];

            // 处理 body 中的列级 comment
            let colComments = [];
            let cleanedBody = body.replace(
                /(\s*)([`"]?\w+[`"]?)\s+([^,\n]+?)\s+COMMENT\s+'([^']+)'/gi,
                (m, leading, colNameRaw, colDef, colComment) => {
                    const colName = colNameRaw.replace(/[`"]/g, '');
                    colComments.push(`COMMENT ON COLUMN "${tableName}"."${colName}" IS '${colComment.replace(/'/g, "''")}';`);
                    let cleanedDef = colDef.replace(/\s+AUTO_INCREMENT\b/gi, '').trim();
                    cleanedDef = convertColumnType(cleanedDef);
                    if (/AUTO_INCREMENT/i.test(colDef)) {
                        cleanedDef += ' GENERATED BY DEFAULT AS IDENTITY';
                    }
                    return `${leading}"${colName}" ${cleanedDef}`;
                }
            );

            // 处理未匹配到 comment 但带 auto_increment 的列
            cleanedBody = cleanedBody.replace(
                /(\s*)([`"]?\w+[`"]?)\s+([^,\n]+?)\s+AUTO_INCREMENT\b/gi,
                (m, leading, colNameRaw, colDef) => {
                    const colName = colNameRaw.replace(/[`"]/g, '');
                    let cleanedDef = convertColumnType(colDef).trim();
                    return `${leading}"${colName}" ${cleanedDef} GENERATED BY DEFAULT AS IDENTITY`;
                }
            );

            // 处理普通列（无 comment 无 auto_increment）
            cleanedBody = cleanedBody.replace(
                /(\s*)([`"]?\w+[`"]?)\s+([^,\n]+?)(?=,|\n|$)/gi,
                (m, leading, colNameRaw, colDef) => {
                    const colName = colNameRaw.replace(/[`"]/g, '');
                    if (colName.toLowerCase() === 'primary' || colName.toLowerCase() === 'unique' || colName.toLowerCase() === 'key' || colName.toLowerCase() === 'constraint' || colName.toLowerCase() === 'index' || colName.toLowerCase() === 'foreign') {
                        return m; // 约束行不处理
                    }
                    let cleanedDef = convertColumnType(colDef).trim();
                    return `${leading}"${colName}" ${cleanedDef}`;
                }
            );

            // 约束转换：先处理 UNIQUE KEY，再处理 PRIMARY KEY，最后收集普通 KEY
            cleanedBody = cleanedBody
                .replace(/UNIQUE\s+KEY\s+([`"]?\w+[`"]?)\s*\(([^)]+)\)(?:\s+COMMENT\s+'([^']+)')?/gi, (m, name, cols, cmt) => {
                    const quotedCols = cols.split(',').map(c => `"${c.replace(/[`"]/g, '').trim()}"`).join(',');
                    let result = `UNIQUE (${quotedCols})`;
                    if (cmt) {
                        result += ` /* ${cmt} */`;
                    }
                    return result;
                })
                .replace(/PRIMARY\s+KEY\s+\(([^)]+)\)/gi, (m, cols) => {
                    const quotedCols = cols.split(',').map(c => `"${c.replace(/[`"]/g, '').trim()}"`).join(',');
                    return `PRIMARY KEY (${quotedCols})`;
                });

            // 收集普通索引并从 body 中删除（避免匹配到 UNIQUE KEY）
            cleanedBody = cleanedBody.replace(
                /(?<!UNIQUE\s+)KEY\s+([`"]?\w+[`"]?)\s*\(([^)]+)\)/gi,
                (m, idxNameRaw, cols) => {
                    const idxName = idxNameRaw.replace(/[`"]/g, '');
                    const quotedCols = cols.split(',').map(c => `"${c.replace(/[`"]/g, '').trim()}"`).join(',');
                    indexes.push(`CREATE INDEX "${idxName}" ON "${tableName}" (${quotedCols});`);
                    return '';
                }
            );

            // 移除 body 中残留的 AUTO_INCREMENT
            cleanedBody = cleanedBody.replace(/\s+AUTO_INCREMENT\b/gi, '');

            // 清理因删除 KEY 行产生的多余逗号（\) 还未拼接，只需清理 body 末尾的逗号）
            cleanedBody = cleanedBody.replace(/,\s*,/g, ',').replace(/,\s*$/g, '');

            let result = `CREATE TABLE "${tableName}" (${cleanedBody});`;
            if (tableComment) {
                result += `\nCOMMENT ON TABLE "${tableName}" IS '${tableComment.replace(/'/g, "''")}';`;
            }
            if (colComments.length > 0) {
                result += '\n' + colComments.join('\n');
            }
            if (indexes.length > 0) {
                result += '\n' + indexes.join('\n');
            }
            return result;
        }
    );
}

function convert(inputFile, outputFile, options = {}) {
    let sql = fs.readFileSync(inputFile, 'utf-8');

    // 1. 移除 SET NAMES / FOREIGN_KEY_CHECKS
    sql = sql.replace(/^SET NAMES .*?;\s*$/gmi, '');
    sql = sql.replace(/^SET FOREIGN_KEY_CHECKS = \d+;\s*$/gmi, '');

    // 2. USE database 语句移除
    sql = sql.replace(/^USE .*?;\s*$/gmi, '');

    // 3. sysdate() -> current_timestamp
    sql = sql.replace(/\bsysdate\s*\(\s*\)/gi, 'current_timestamp');

    // 4. 处理 CREATE DATABASE
    sql = sql.replace(/DROP DATABASE IF EXISTS\s+`?([^`\n]+)`?\s*;/gi, 'DROP DATABASE IF EXISTS "$1";');
    sql = sql.replace(/CREATE DATABASE\s+`?([^`\n]+)`?\s+DEFAULT CHARACTER SET .*?;/gi, 'CREATE DATABASE "$1";');

    // 5. 处理 DROP TABLE IF EXISTS
    sql = sql.replace(/DROP TABLE IF EXISTS\s+([`"]?\w+[`"]?)\s*;/gi, 'DROP TABLE IF EXISTS $1 CASCADE;');

    // 6. 转换 CREATE TABLE
    sql = convertCreateTable(sql);

    // 7. SELECT 1 FROM DUAL -> SELECT 1
    sql = sql.replace(/SELECT\s+1\s+FROM\s+DUAL/gi, 'SELECT 1');

    // 8. IFNULL -> COALESCE
    sql = sql.replace(/\bIFNULL\s*\(/gi, 'COALESCE(');

    // 9. GROUP_CONCAT -> STRING_AGG
    sql = sql.replace(/\bGROUP_CONCAT\s*\((.*?)\)/gi, 'STRING_AGG($1, \',\')');

    // 10. DATE_FORMAT -> TO_CHAR
    sql = sql.replace(/\bDATE_FORMAT\s*\(([^,]+),\s*'([^']+)'\s*\)/gi, (m, col, fmt) => {
        const pgFmt = fmt
            .replace(/%Y/g, 'YYYY')
            .replace(/%m/g, 'MM')
            .replace(/%d/g, 'DD')
            .replace(/%H/g, 'HH24')
            .replace(/%i/g, 'MI')
            .replace(/%s/g, 'SS');
        return `TO_CHAR(${col}, '${pgFmt}')`;
    });

    // 11. 反引号统一替换为双引号（针对剩余部分）
    sql = stripBackticks(sql);

    // 11.5 修复 foreign key 中 references 被误加引号的问题
    sql = sql.replace(/"references"/gi, 'references');
    sql = sql.replace(/references\s+(\w+)\(/gi, (m, tableName) => `references "${tableName}"(`);

    // 12. 移除 MySQL 特有的插入语法：INSERT INTO table VALUES(...),(...) 拆分成多行？Kingbase 支持多值插入
    // 13. 清理多余空行
    sql = sql.replace(/\n{3,}/g, '\n\n');

    // 14. 针对 ry-config.sql：不直接修改 content 字段（避免破坏 YAML 格式），
    //     而是生成单独的 UPDATE 脚本用于更新 Kingbase 连接配置
    if (options.updateNacosConfig) {
        const updateSql = [
            "-- 更新 Nacos 配置中心的 MySQL 连接为 Kingbase",
            `UPDATE "config_info" SET "content" = REPLACE("content", 'com.mysql.cj.jdbc.Driver', 'com.kingbase8.Driver') WHERE "content" LIKE '%com.mysql.cj.jdbc.Driver%';`,
            `UPDATE "config_info" SET "content" = REPLACE("content", 'jdbc:mysql://localhost:3306/ry-cloud?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8', 'jdbc:kingbase8://121.40.112.55:54321/ry-cloud') WHERE "content" LIKE '%jdbc:mysql://localhost:3306/ry-cloud%';`,
            `UPDATE "config_info" SET "content" = REPLACE("content", 'jdbc:mysql://localhost:3306/ry-config?characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useUnicode=true&useSSL=false&serverTimezone=UTC', 'jdbc:kingbase8://121.40.112.55:54321/ry-config') WHERE "content" LIKE '%jdbc:mysql://localhost:3306/ry-config%';`,
            `UPDATE "config_info" SET "content" = REPLACE("content", 'SELECT 1 FROM DUAL', 'SELECT 1') WHERE "content" LIKE '%SELECT 1 FROM DUAL%';`,
            `UPDATE "config_info" SET "content" = REPLACE("content", 'helperDialect: mysql', 'helperDialect: postgresql') WHERE "content" LIKE '%helperDialect: mysql%';`,
            `UPDATE "config_info" SET "content" = REPLACE("content", 'password: password', 'password: HGZJ2026') WHERE "content" LIKE '%password: password%';`,
            ""
        ].join("\n");
        const updateFile = outputFile.replace(/\.sql$/, '_updates.sql');
        fs.writeFileSync(updateFile, updateSql, 'utf-8');
        console.log(`Generated: ${updateFile}`);
    }

    fs.writeFileSync(outputFile, sql, 'utf-8');
    console.log(`Converted: ${inputFile} -> ${outputFile}`);
}

const files = [
    ['sql/ry_20260417.sql', 'sql/kingbase/ry-cloud.sql', false],
    ['sql/ry_config_20250902.sql', 'sql/kingbase/ry-config.sql', true],
    ['sql/ry_seata_20210128.sql', 'sql/kingbase/ry-seata.sql', false],
    ['sql/quartz.sql', 'sql/kingbase/quartz.sql', false],
];

const outDir = path.join(__dirname, '..', 'sql', 'kingbase');
if (!fs.existsSync(outDir)) {
    fs.mkdirSync(outDir, { recursive: true });
}

files.forEach(([input, output, updateNacosConfig]) => {
    const inputPath = path.join(__dirname, '..', input);
    const outputPath = path.join(__dirname, '..', output);
    if (fs.existsSync(inputPath)) {
        convert(inputPath, outputPath, { updateNacosConfig });
    } else {
        console.warn(`Not found: ${inputPath}`);
    }
});
