CREATE TABLE IF NOT EXISTS nc_business_message (
  message_id bigint not null GENERATED BY DEFAULT AS IDENTITY,
  message_type varchar(64) not null,
  title varchar(200) not null,
  content text,
  business_type varchar(64) not null,
  business_id bigint,
  jump_target varchar(255) not null,
  read_status char(1) default '0',
  receiver_user_id bigint,
  receiver_user_name varchar(64) default '',
  event_time timestamp,
  del_flag char(1) default '0',
  create_by varchar(64) default '',
  create_time timestamp,
  update_by varchar(64) default '',
  update_time timestamp,
  remark varchar(500) default null,
  CONSTRAINT pk_nc_business_message PRIMARY KEY (message_id)
);

CREATE INDEX IF NOT EXISTS idx_nc_business_message_user_time ON nc_business_message(receiver_user_name, event_time desc);

ALTER TABLE survey_enterprise ADD COLUMN IF NOT EXISTS address varchar(255) default '';
ALTER TABLE survey_enterprise ADD COLUMN IF NOT EXISTS longitude varchar(32) default '';
ALTER TABLE survey_enterprise ADD COLUMN IF NOT EXISTS latitude varchar(32) default '';
ALTER TABLE survey_enterprise ADD COLUMN IF NOT EXISTS geocode_status varchar(32) default '';
ALTER TABLE survey_enterprise ADD COLUMN IF NOT EXISTS geocode_message varchar(500) default '';

INSERT INTO sys_config(config_name, config_key, config_value, config_type, create_by, create_time, remark)
VALUES
('高德地图前端 Key', 'nocontact.amap.frontendKey', '', 'N', 'admin', current_timestamp, '公共支撑-高德地图'),
('高德地图安全码', 'nocontact.amap.securityJsCode', '', 'N', 'admin', current_timestamp, '公共支撑-高德地图'),
('高德地理编码 Key', 'nocontact.amap.geocodeKey', '', 'N', 'admin', current_timestamp, '公共支撑-高德地图'),
('公共文件根路径', 'nocontact.file.basePath', '', 'N', 'admin', current_timestamp, '公共支撑-业务设置'),
('预警推送开关', 'nocontact.warning.pushEnabled', '1', 'N', 'admin', current_timestamp, '公共支撑-业务设置'),
('默认报告周期', 'nocontact.report.defaultPeriod', 'quarter', 'N', 'admin', current_timestamp, '公共支撑-业务设置'),
('外部系统总开关', 'nocontact.integration.globalEnabled', '1', 'N', 'admin', current_timestamp, '公共支撑-业务设置')
ON CONFLICT DO NOTHING;

INSERT INTO sys_menu(menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark)
VALUES
(3600, '公共支撑', 0, 8, 'support', 'Layout', '', '', 1, 0, 'M', '0', '0', '', 'dashboard', 'admin', current_timestamp, 'admin', current_timestamp, '公共支撑'),
(3610, '我的待办', 3600, 1, 'todo', 'nocontact/support/todo/index', '', '', 1, 0, 'C', '0', '0', 'nocontact:support:todo:list', 'list', 'admin', current_timestamp, 'admin', current_timestamp, '我的待办'),
(3620, '消息中心', 3600, 2, 'message', 'nocontact/support/message/index', '', '', 1, 0, 'C', '0', '0', 'nocontact:support:message:list', 'message', 'admin', current_timestamp, 'admin', current_timestamp, '消息中心'),
(3630, '业务设置', 3600, 3, 'settings', 'nocontact/support/settings/index', '', '', 1, 0, 'C', '0', '0', 'nocontact:support:settings:list', 'build', 'admin', current_timestamp, 'admin', current_timestamp, '业务设置')
ON CONFLICT (menu_id) DO UPDATE SET
  menu_name = EXCLUDED.menu_name,
  parent_id = EXCLUDED.parent_id,
  order_num = EXCLUDED.order_num,
  path = EXCLUDED.path,
  component = EXCLUDED.component,
  perms = EXCLUDED.perms,
  update_by = 'admin',
  update_time = current_timestamp,
  remark = EXCLUDED.remark;
