-- 营商无感业务模块 001：数据融合与检测预警 P0

CREATE TABLE IF NOT EXISTS nc_fusion_indicator (
  indicator_id bigint not null GENERATED BY DEFAULT AS IDENTITY,
  year_name varchar(32) not null,
  first_level varchar(120) not null,
  second_level varchar(120) not null,
  indicator_name varchar(200) not null,
  scoring_rule text,
  responsible_unit varchar(300) default '',
  data_source varchar(120) default '',
  status char(1) default '0',
  del_flag char(1) default '0',
  create_by varchar(64) default '',
  create_time timestamp,
  update_by varchar(64) default '',
  update_time timestamp,
  remark varchar(500) default null,
  CONSTRAINT pk_nc_fusion_indicator PRIMARY KEY (indicator_id)
);

COMMENT ON TABLE nc_fusion_indicator IS '营商监测指标目录';
COMMENT ON COLUMN nc_fusion_indicator.status IS '状态（0启用 1停用）';

CREATE TABLE IF NOT EXISTS nc_fusion_collection_task (
  task_id bigint not null GENERATED BY DEFAULT AS IDENTITY,
  task_name varchar(120) not null,
  task_type varchar(24) not null,
  task_status varchar(24) default 'draft',
  target_level varchar(24) default 'province',
  indicator_id bigint,
  indicator_name varchar(200) default '',
  data_targets varchar(300) default '',
  source_type varchar(24) default 'form',
  fill_cycle varchar(24) default 'quarter',
  schedule_mode varchar(24) default 'manual',
  cron_expression varchar(120) default '',
  audit_enabled char(1) default '1',
  owner_name varchar(64) default '',
  data_count bigint default 0,
  last_run_time timestamp,
  del_flag char(1) default '0',
  create_by varchar(64) default '',
  create_time timestamp,
  update_by varchar(64) default '',
  update_time timestamp,
  remark varchar(500) default null,
  CONSTRAINT pk_nc_fusion_collection_task PRIMARY KEY (task_id)
);

COMMENT ON TABLE nc_fusion_collection_task IS '数据采集任务';
COMMENT ON COLUMN nc_fusion_collection_task.task_type IS '任务类型（fill填报 auto自动采集 api接口对接）';
COMMENT ON COLUMN nc_fusion_collection_task.task_status IS '任务状态（draft草稿 published已发布 running执行中 done已完成 error异常）';
COMMENT ON COLUMN nc_fusion_collection_task.source_type IS '数据源类型（database数据库 excel模板 api接口 form在线填报）';

CREATE TABLE IF NOT EXISTS nc_warning_rule (
  rule_id bigint not null GENERATED BY DEFAULT AS IDENTITY,
  rule_name varchar(120) not null,
  indicator_id bigint not null,
  indicator_name varchar(200) default '',
  warning_level char(1) not null,
  threshold_type varchar(32) default 'target',
  threshold_value numeric(18,4) not null,
  trigger_condition varchar(24) default 'lt',
  trigger_frequency varchar(24) default 'daily',
  push_channels varchar(120) default 'site',
  push_targets varchar(300) default '负责人',
  content_template text,
  effective_mode varchar(24) default 'now',
  effective_time timestamp,
  status char(1) default '0',
  del_flag char(1) default '0',
  create_by varchar(64) default '',
  create_time timestamp,
  update_by varchar(64) default '',
  update_time timestamp,
  remark varchar(500) default null,
  CONSTRAINT pk_nc_warning_rule PRIMARY KEY (rule_id)
);

COMMENT ON TABLE nc_warning_rule IS '预警规则';
COMMENT ON COLUMN nc_warning_rule.warning_level IS '预警级别（1红色 2橙色 3黄色）';
COMMENT ON COLUMN nc_warning_rule.status IS '状态（0启用 1停用）';

CREATE TABLE IF NOT EXISTS nc_warning_message (
  message_id bigint not null GENERATED BY DEFAULT AS IDENTITY,
  rule_id bigint,
  rule_name varchar(120) default '',
  indicator_id bigint,
  indicator_name varchar(200) default '',
  warning_level char(1) not null,
  region_name varchar(64) default '',
  current_value numeric(18,4),
  threshold_value numeric(18,4),
  push_channels varchar(120) default '',
  receivers varchar(300) default '',
  message_status varchar(24) default 'sent',
  trigger_time timestamp,
  handle_time timestamp,
  del_flag char(1) default '0',
  create_by varchar(64) default '',
  create_time timestamp,
  update_by varchar(64) default '',
  update_time timestamp,
  remark varchar(500) default null,
  CONSTRAINT pk_nc_warning_message PRIMARY KEY (message_id)
);

COMMENT ON TABLE nc_warning_message IS '预警消息';
COMMENT ON COLUMN nc_warning_message.message_status IS '状态（sent已发送 read已读 handled已处理 archived已归档）';

CREATE INDEX IF NOT EXISTS idx_nc_fusion_indicator_name ON nc_fusion_indicator(indicator_name);
CREATE INDEX IF NOT EXISTS idx_nc_fusion_indicator_unit ON nc_fusion_indicator(responsible_unit);
CREATE INDEX IF NOT EXISTS idx_nc_fusion_task_status ON nc_fusion_collection_task(task_status);
CREATE INDEX IF NOT EXISTS idx_nc_warning_rule_indicator ON nc_warning_rule(indicator_id);
CREATE INDEX IF NOT EXISTS idx_nc_warning_message_level ON nc_warning_message(warning_level);
CREATE INDEX IF NOT EXISTS idx_nc_warning_message_trigger ON nc_warning_message(trigger_time);

INSERT INTO nc_fusion_indicator(indicator_id, year_name, first_level, second_level, indicator_name, scoring_rule, responsible_unit, data_source, status, create_by, create_time)
SELECT 1001, '2026(省直)', '工作情况', '任务落实', '监测工作开展情况', '参与营商环境监测工作的责任单位，是否严格按照年度营商环境监测工作方案开展工作、报送数据；未按要求反馈监测数据、分值细项、计分依据或数据有误的按项扣分。', '省委督查室、省政府督查室、省优化办', '指标汇总表', '0', 'admin', current_timestamp
WHERE NOT EXISTS (SELECT 1 FROM nc_fusion_indicator WHERE indicator_id = 1001);

INSERT INTO nc_fusion_indicator(indicator_id, year_name, first_level, second_level, indicator_name, scoring_rule, responsible_unit, data_source, status, create_by, create_time)
SELECT 1002, '2026(省直)', '工作情况', '服务效能', '政务数据共享应用情况', '监测省直相关单位是否按要求向省大数据总枢纽平台共享数据，涵盖数据完整性、及时性、准确性及共享互认情况。', '省委督查室、省政府督查室、省优化办（配合：省数据局）', '指标汇总表', '0', 'admin', current_timestamp
WHERE NOT EXISTS (SELECT 1 FROM nc_fusion_indicator WHERE indicator_id = 1002);

INSERT INTO nc_fusion_indicator(indicator_id, year_name, first_level, second_level, indicator_name, scoring_rule, responsible_unit, data_source, status, create_by, create_time)
SELECT 1003, '2026', '服务效能', '政务服务', '数字政务能力', '政务服务事项网上申办率达到基准值不扣分，每低于基准值扣分；有效数据需求数和数据目录数按规则计分。', '省数据局', '指标汇总表', '0', 'admin', current_timestamp
WHERE NOT EXISTS (SELECT 1 FROM nc_fusion_indicator WHERE indicator_id = 1003);

INSERT INTO nc_fusion_indicator(indicator_id, year_name, first_level, second_level, indicator_name, scoring_rule, responsible_unit, data_source, status, create_by, create_time)
SELECT 1004, '2026', '服务效能', '道路交通服务', '省养普通国省道优良路率', '市州与县市区按路况目标达成情况、排名和扣分规则计分。', '省交通运输厅', '指标汇总表', '0', 'admin', current_timestamp
WHERE NOT EXISTS (SELECT 1 FROM nc_fusion_indicator WHERE indicator_id = 1004);

INSERT INTO nc_fusion_indicator(indicator_id, year_name, first_level, second_level, indicator_name, scoring_rule, responsible_unit, data_source, status, create_by, create_time)
SELECT 1005, '2026', '经营环境', '涉企监管', '规范涉企行政检查', '统计各地涉企行政检查相关数据，排序后按档次计分。', '省司法厅', '指标汇总表', '0', 'admin', current_timestamp
WHERE NOT EXISTS (SELECT 1 FROM nc_fusion_indicator WHERE indicator_id = 1005);

INSERT INTO nc_fusion_indicator(indicator_id, year_name, first_level, second_level, indicator_name, scoring_rule, responsible_unit, data_source, status, create_by, create_time)
SELECT 1006, '2026', '信用建设', '政务诚信', '清理拖欠企业账款', '市州直接采用省政府推动高质量发展大抓落实督查激励该项目数据折算计分。', '省工信厅', '指标汇总表', '0', 'admin', current_timestamp
WHERE NOT EXISTS (SELECT 1 FROM nc_fusion_indicator WHERE indicator_id = 1006);

INSERT INTO nc_fusion_collection_task(task_id, task_name, task_type, task_status, target_level, indicator_id, indicator_name, data_targets, source_type, fill_cycle, schedule_mode, cron_expression, audit_enabled, owner_name, data_count, last_run_time, create_by, create_time)
SELECT 2001, '2026省直监测数据季度报送', 'fill', 'published', 'province', 1001, '监测工作开展情况', '省直责任单位', 'form', 'quarter', 'manual', '', '1', '省优化办', 0, NULL, 'admin', current_timestamp
WHERE NOT EXISTS (SELECT 1 FROM nc_fusion_collection_task WHERE task_id = 2001);

INSERT INTO nc_fusion_collection_task(task_id, task_name, task_type, task_status, target_level, indicator_id, indicator_name, data_targets, source_type, fill_cycle, schedule_mode, cron_expression, audit_enabled, owner_name, data_count, last_run_time, create_by, create_time)
SELECT 2002, '数字政务能力办件数据自动采集', 'api', 'running', 'city', 1003, '数字政务能力', '14个市州', 'api', 'month', 'timed', '0 0 2 1 * ?', '1', '省数据局', 12860, current_timestamp, 'admin', current_timestamp
WHERE NOT EXISTS (SELECT 1 FROM nc_fusion_collection_task WHERE task_id = 2002);

INSERT INTO nc_fusion_collection_task(task_id, task_name, task_type, task_status, target_level, indicator_id, indicator_name, data_targets, source_type, fill_cycle, schedule_mode, cron_expression, audit_enabled, owner_name, data_count, last_run_time, create_by, create_time)
SELECT 2003, '涉企行政检查数据月度导入', 'fill', 'done', 'city', 1005, '规范涉企行政检查', '市州及县市区', 'excel', 'month', 'manual', '', '1', '省司法厅', 560, current_timestamp, 'admin', current_timestamp
WHERE NOT EXISTS (SELECT 1 FROM nc_fusion_collection_task WHERE task_id = 2003);

INSERT INTO nc_warning_rule(rule_id, rule_name, indicator_id, indicator_name, warning_level, threshold_type, threshold_value, trigger_condition, trigger_frequency, push_channels, push_targets, content_template, effective_mode, status, create_by, create_time)
SELECT 3001, '监测数据逾期未报红色预警', 1001, '监测工作开展情况', '1', 'custom', 1, 'gt', 'daily', 'site,sms', '监测项负责人,管理人员', '{{指标名称}}存在逾期未报，请立即核查。', 'now', '0', 'admin', current_timestamp
WHERE NOT EXISTS (SELECT 1 FROM nc_warning_rule WHERE rule_id = 3001);

INSERT INTO nc_warning_rule(rule_id, rule_name, indicator_id, indicator_name, warning_level, threshold_type, threshold_value, trigger_condition, trigger_frequency, push_channels, push_targets, content_template, effective_mode, status, create_by, create_time)
SELECT 3002, '数字政务能力低于基准橙色预警', 1003, '数字政务能力', '2', 'target', 80, 'lt', 'daily', 'site,email', '监测项负责人', '{{地区}}数字政务能力当前值{{当前值}}低于阈值{{阈值}}。', 'now', '0', 'admin', current_timestamp
WHERE NOT EXISTS (SELECT 1 FROM nc_warning_rule WHERE rule_id = 3002);

INSERT INTO nc_warning_message(message_id, rule_id, rule_name, indicator_id, indicator_name, warning_level, region_name, current_value, threshold_value, push_channels, receivers, message_status, trigger_time, create_by, create_time)
SELECT 4001, 3001, '监测数据逾期未报红色预警', 1001, '监测工作开展情况', '1', '省直单位', 3, 1, 'site,sms', '省优化办管理员', 'sent', current_timestamp, 'admin', current_timestamp
WHERE NOT EXISTS (SELECT 1 FROM nc_warning_message WHERE message_id = 4001);

INSERT INTO nc_warning_message(message_id, rule_id, rule_name, indicator_id, indicator_name, warning_level, region_name, current_value, threshold_value, push_channels, receivers, message_status, trigger_time, create_by, create_time)
SELECT 4002, 3002, '数字政务能力低于基准橙色预警', 1003, '数字政务能力', '2', '湘西州', 72, 80, 'site,email', '省数据局负责人', 'read', current_timestamp - interval '1 day', 'admin', current_timestamp
WHERE NOT EXISTS (SELECT 1 FROM nc_warning_message WHERE message_id = 4002);

INSERT INTO nc_warning_message(message_id, rule_id, rule_name, indicator_id, indicator_name, warning_level, region_name, current_value, threshold_value, push_channels, receivers, message_status, trigger_time, handle_time, create_by, create_time)
SELECT 4003, 3002, '数字政务能力低于基准橙色预警', 1003, '数字政务能力', '3', '怀化市', 78, 80, 'site', '省数据局负责人', 'handled', current_timestamp - interval '2 days', current_timestamp - interval '1 day', 'admin', current_timestamp
WHERE NOT EXISTS (SELECT 1 FROM nc_warning_message WHERE message_id = 4003);

-- 营商数据融合菜单
INSERT INTO sys_menu(menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark)
SELECT 3000, '营商数据融合', 0, 1, 'fusion', NULL, '', '', 1, 0, 'M', '0', '0', '', 'database', 'admin', current_timestamp, '', NULL, '营商数据融合目录'
WHERE NOT EXISTS (SELECT 1 FROM sys_menu WHERE menu_id = 3000);

INSERT INTO sys_menu(menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark)
SELECT 3010, '采集任务管理', 3000, 1, 'task', 'nocontact/fusion/task/index', '', '', 1, 0, 'C', '0', '0', 'fusion:task:list', 'list', 'admin', current_timestamp, '', NULL, '采集任务管理'
WHERE NOT EXISTS (SELECT 1 FROM sys_menu WHERE menu_id = 3010);

INSERT INTO sys_menu(menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark)
SELECT 3020, '指标目录', 3000, 2, 'indicator', 'nocontact/fusion/indicator/index', '', '', 1, 0, 'C', '0', '0', 'fusion:indicator:list', 'tree-table', 'admin', current_timestamp, '', NULL, '指标目录'
WHERE NOT EXISTS (SELECT 1 FROM sys_menu WHERE menu_id = 3020);

-- 检测预警中心菜单
INSERT INTO sys_menu(menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark)
SELECT 3200, '检测预警中心', 0, 3, 'warning', NULL, '', '', 1, 0, 'M', '0', '0', '', 'alert', 'admin', current_timestamp, '', NULL, '检测预警中心目录'
WHERE NOT EXISTS (SELECT 1 FROM sys_menu WHERE menu_id = 3200);

INSERT INTO sys_menu(menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark)
SELECT 3210, '预警规则管理', 3200, 1, 'rule', 'nocontact/warning/rule/index', '', '', 1, 0, 'C', '0', '0', 'warning:rule:list', 'dict', 'admin', current_timestamp, '', NULL, '预警规则管理'
WHERE NOT EXISTS (SELECT 1 FROM sys_menu WHERE menu_id = 3210);

INSERT INTO sys_menu(menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark)
SELECT 3220, '预警消息管理', 3200, 2, 'message', 'nocontact/warning/message/index', '', '', 1, 0, 'C', '0', '0', 'warning:message:list', 'message', 'admin', current_timestamp, '', NULL, '预警消息管理'
WHERE NOT EXISTS (SELECT 1 FROM sys_menu WHERE menu_id = 3220);

INSERT INTO sys_menu(menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark)
SELECT 3230, '分级预警看板', 3200, 3, 'dashboard', 'nocontact/warning/dashboard/index', '', '', 1, 0, 'C', '0', '0', 'warning:dashboard:query', 'dashboard', 'admin', current_timestamp, '', NULL, '分级预警看板'
WHERE NOT EXISTS (SELECT 1 FROM sys_menu WHERE menu_id = 3230);

INSERT INTO sys_menu(menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark)
SELECT 3011, '采集任务查询', 3010, 1, '', '', '', '', 1, 0, 'F', '0', '0', 'fusion:task:query', '#', 'admin', current_timestamp, '', NULL, ''
WHERE NOT EXISTS (SELECT 1 FROM sys_menu WHERE menu_id = 3011);

INSERT INTO sys_menu(menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark)
SELECT 3012, '采集任务新增', 3010, 2, '', '', '', '', 1, 0, 'F', '0', '0', 'fusion:task:add', '#', 'admin', current_timestamp, '', NULL, ''
WHERE NOT EXISTS (SELECT 1 FROM sys_menu WHERE menu_id = 3012);

INSERT INTO sys_menu(menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark)
SELECT 3013, '采集任务修改', 3010, 3, '', '', '', '', 1, 0, 'F', '0', '0', 'fusion:task:edit', '#', 'admin', current_timestamp, '', NULL, ''
WHERE NOT EXISTS (SELECT 1 FROM sys_menu WHERE menu_id = 3013);

INSERT INTO sys_menu(menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark)
SELECT 3014, '采集任务删除', 3010, 4, '', '', '', '', 1, 0, 'F', '0', '0', 'fusion:task:remove', '#', 'admin', current_timestamp, '', NULL, ''
WHERE NOT EXISTS (SELECT 1 FROM sys_menu WHERE menu_id = 3014);

INSERT INTO sys_menu(menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark)
SELECT 3021, '指标查询', 3020, 1, '', '', '', '', 1, 0, 'F', '0', '0', 'fusion:indicator:query', '#', 'admin', current_timestamp, '', NULL, ''
WHERE NOT EXISTS (SELECT 1 FROM sys_menu WHERE menu_id = 3021);

INSERT INTO sys_menu(menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark)
SELECT 3022, '指标新增', 3020, 2, '', '', '', '', 1, 0, 'F', '0', '0', 'fusion:indicator:add', '#', 'admin', current_timestamp, '', NULL, ''
WHERE NOT EXISTS (SELECT 1 FROM sys_menu WHERE menu_id = 3022);

INSERT INTO sys_menu(menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark)
SELECT 3023, '指标修改', 3020, 3, '', '', '', '', 1, 0, 'F', '0', '0', 'fusion:indicator:edit', '#', 'admin', current_timestamp, '', NULL, ''
WHERE NOT EXISTS (SELECT 1 FROM sys_menu WHERE menu_id = 3023);

INSERT INTO sys_menu(menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark)
SELECT 3024, '指标删除', 3020, 4, '', '', '', '', 1, 0, 'F', '0', '0', 'fusion:indicator:remove', '#', 'admin', current_timestamp, '', NULL, ''
WHERE NOT EXISTS (SELECT 1 FROM sys_menu WHERE menu_id = 3024);

INSERT INTO sys_menu(menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark)
SELECT 3211, '预警规则查询', 3210, 1, '', '', '', '', 1, 0, 'F', '0', '0', 'warning:rule:query', '#', 'admin', current_timestamp, '', NULL, ''
WHERE NOT EXISTS (SELECT 1 FROM sys_menu WHERE menu_id = 3211);

INSERT INTO sys_menu(menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark)
SELECT 3212, '预警规则新增', 3210, 2, '', '', '', '', 1, 0, 'F', '0', '0', 'warning:rule:add', '#', 'admin', current_timestamp, '', NULL, ''
WHERE NOT EXISTS (SELECT 1 FROM sys_menu WHERE menu_id = 3212);

INSERT INTO sys_menu(menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark)
SELECT 3213, '预警规则修改', 3210, 3, '', '', '', '', 1, 0, 'F', '0', '0', 'warning:rule:edit', '#', 'admin', current_timestamp, '', NULL, ''
WHERE NOT EXISTS (SELECT 1 FROM sys_menu WHERE menu_id = 3213);

INSERT INTO sys_menu(menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark)
SELECT 3214, '预警规则删除', 3210, 4, '', '', '', '', 1, 0, 'F', '0', '0', 'warning:rule:remove', '#', 'admin', current_timestamp, '', NULL, ''
WHERE NOT EXISTS (SELECT 1 FROM sys_menu WHERE menu_id = 3214);

INSERT INTO sys_menu(menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark)
SELECT 3221, '预警消息查询', 3220, 1, '', '', '', '', 1, 0, 'F', '0', '0', 'warning:message:query', '#', 'admin', current_timestamp, '', NULL, ''
WHERE NOT EXISTS (SELECT 1 FROM sys_menu WHERE menu_id = 3221);

INSERT INTO sys_menu(menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark)
SELECT 3222, '预警消息处理', 3220, 2, '', '', '', '', 1, 0, 'F', '0', '0', 'warning:message:edit', '#', 'admin', current_timestamp, '', NULL, ''
WHERE NOT EXISTS (SELECT 1 FROM sys_menu WHERE menu_id = 3222);

INSERT INTO sys_menu(menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark)
SELECT 3223, '预警消息删除', 3220, 3, '', '', '', '', 1, 0, 'F', '0', '0', 'warning:message:remove', '#', 'admin', current_timestamp, '', NULL, ''
WHERE NOT EXISTS (SELECT 1 FROM sys_menu WHERE menu_id = 3223);
