-- 营商无感业务模块 005：报告生成任务与快照归档闭环

CREATE TABLE IF NOT EXISTS nc_report_template (
  template_id bigint not null GENERATED BY DEFAULT AS IDENTITY,
  template_name varchar(160) not null,
  report_type varchar(32) default 'overall',
  sections text,
  data_scope varchar(300) default '',
  style_config text,
  version_no int default 1,
  status char(1) default '0',
  del_flag char(1) default '0',
  create_by varchar(64) default '',
  create_time timestamp,
  update_by varchar(64) default '',
  update_time timestamp,
  remark varchar(500) default null,
  CONSTRAINT pk_nc_report_template PRIMARY KEY (template_id)
);

CREATE TABLE IF NOT EXISTS nc_report_generation_task (
  task_id bigint not null GENERATED BY DEFAULT AS IDENTITY,
  task_name varchar(160) not null,
  template_id bigint,
  template_name varchar(160) default '',
  report_period varchar(64) default '',
  report_scope varchar(160) default '',
  generate_mode varchar(32) default 'manual',
  task_status varchar(32) default 'pending',
  generated_file_name varchar(260) default '',
  generated_word_file_name varchar(260) default '',
  generated_excel_file_name varchar(260) default '',
  template_version int,
  generated_by varchar(64) default '',
  snapshot_content text,
  generated_time timestamp,
  del_flag char(1) default '0',
  create_by varchar(64) default '',
  create_time timestamp,
  update_by varchar(64) default '',
  update_time timestamp,
  remark varchar(500) default null,
  CONSTRAINT pk_nc_report_generation_task PRIMARY KEY (task_id)
);

CREATE TABLE IF NOT EXISTS nc_report_generation_snapshot (
  snapshot_id bigint not null GENERATED BY DEFAULT AS IDENTITY,
  task_id bigint not null,
  task_name varchar(160) default '',
  template_name varchar(160) default '',
  report_period varchar(64) default '',
  report_scope varchar(160) default '',
  generated_word_file_name varchar(260) default '',
  generated_excel_file_name varchar(260) default '',
  template_version int,
  generated_by varchar(64) default '',
  snapshot_content text,
  generated_time timestamp,
  create_by varchar(64) default '',
  create_time timestamp,
  remark varchar(500) default null,
  CONSTRAINT pk_nc_report_generation_snapshot PRIMARY KEY (snapshot_id)
);

ALTER TABLE nc_report_generation_task ADD COLUMN IF NOT EXISTS generated_word_file_name varchar(260) default '';
ALTER TABLE nc_report_generation_task ADD COLUMN IF NOT EXISTS generated_excel_file_name varchar(260) default '';
ALTER TABLE nc_report_generation_task ADD COLUMN IF NOT EXISTS template_version int;
ALTER TABLE nc_report_generation_task ADD COLUMN IF NOT EXISTS generated_by varchar(64) default '';

CREATE INDEX IF NOT EXISTS idx_nc_report_task_status ON nc_report_generation_task(task_status);
CREATE INDEX IF NOT EXISTS idx_nc_report_snapshot_task_time ON nc_report_generation_snapshot(task_id, generated_time);

DELETE FROM sys_menu WHERE menu_id = 3520 OR parent_id = 3520;

INSERT INTO sys_menu(menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark)
VALUES
(3500, '报告自动生成', 0, 7, 'report', NULL, '', '', 1, 0, 'M', '0', '0', '', 'documentation', 'admin', current_timestamp, 'admin', current_timestamp, '报告自动生成'),
(3510, '报告模板管理', 3500, 1, 'template', 'nocontact/report/template/index', '', '', 1, 0, 'C', '0', '0', 'nocontact:report:template:list', 'form', 'admin', current_timestamp, 'admin', current_timestamp, '报告模板管理'),
(3530, '报告生成任务', 3500, 2, 'task', 'nocontact/report/task/index', '', '', 1, 0, 'C', '0', '0', 'nocontact:report:task:list', 'job', 'admin', current_timestamp, 'admin', current_timestamp, '报告生成任务')
ON CONFLICT (menu_id) DO UPDATE SET
  menu_name = EXCLUDED.menu_name,
  parent_id = EXCLUDED.parent_id,
  order_num = EXCLUDED.order_num,
  path = EXCLUDED.path,
  component = EXCLUDED.component,
  query = EXCLUDED.query,
  route_name = EXCLUDED.route_name,
  is_frame = EXCLUDED.is_frame,
  is_cache = EXCLUDED.is_cache,
  menu_type = EXCLUDED.menu_type,
  visible = EXCLUDED.visible,
  status = EXCLUDED.status,
  perms = EXCLUDED.perms,
  icon = EXCLUDED.icon,
  update_by = 'admin',
  update_time = current_timestamp,
  remark = EXCLUDED.remark;

INSERT INTO sys_menu(menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark)
VALUES
(3511, '模板查询', 3510, 1, '', '', '', '', 1, 0, 'F', '0', '0', 'nocontact:report:template:query', '#', 'admin', current_timestamp, 'admin', current_timestamp, ''),
(3512, '模板新增', 3510, 2, '', '', '', '', 1, 0, 'F', '0', '0', 'nocontact:report:template:add', '#', 'admin', current_timestamp, 'admin', current_timestamp, ''),
(3513, '模板修改', 3510, 3, '', '', '', '', 1, 0, 'F', '0', '0', 'nocontact:report:template:edit', '#', 'admin', current_timestamp, 'admin', current_timestamp, ''),
(3514, '模板删除', 3510, 4, '', '', '', '', 1, 0, 'F', '0', '0', 'nocontact:report:template:remove', '#', 'admin', current_timestamp, 'admin', current_timestamp, ''),
(3531, '任务查询', 3530, 1, '', '', '', '', 1, 0, 'F', '0', '0', 'nocontact:report:task:query', '#', 'admin', current_timestamp, 'admin', current_timestamp, ''),
(3532, '任务新增', 3530, 2, '', '', '', '', 1, 0, 'F', '0', '0', 'nocontact:report:task:add', '#', 'admin', current_timestamp, 'admin', current_timestamp, ''),
(3533, '任务生成', 3530, 3, '', '', '', '', 1, 0, 'F', '0', '0', 'nocontact:report:task:edit', '#', 'admin', current_timestamp, 'admin', current_timestamp, ''),
(3534, '任务下载', 3530, 4, '', '', '', '', 1, 0, 'F', '0', '0', 'nocontact:report:task:query', '#', 'admin', current_timestamp, 'admin', current_timestamp, '')
ON CONFLICT (menu_id) DO UPDATE SET
  menu_name = EXCLUDED.menu_name,
  parent_id = EXCLUDED.parent_id,
  order_num = EXCLUDED.order_num,
  path = EXCLUDED.path,
  component = EXCLUDED.component,
  perms = EXCLUDED.perms,
  update_by = 'admin',
  update_time = current_timestamp,
  remark = EXCLUDED.remark;
