-- 营商无感业务模块 010：问题整改闭环（issue #11）
-- 覆盖用户故事：46-52，82-84

-- ============================================================
-- 整改问题台账
-- ============================================================
CREATE TABLE IF NOT EXISTS nc_rectification_issue (
  issue_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  issue_code varchar(64) NOT NULL,
  issue_title varchar(200) NOT NULL,
  source_type varchar(24) DEFAULT 'manual' NOT NULL,
  source_warning_id bigint DEFAULT NULL,
  dept_id bigint DEFAULT NULL,
  warning_level varchar(24) DEFAULT NULL,
  region_name varchar(120) DEFAULT NULL,
  responsible_unit_name varchar(200) DEFAULT NULL,
  responsible_person varchar(64) DEFAULT NULL,
  supervisor_name varchar(64) DEFAULT NULL,
  deadline timestamp DEFAULT NULL,
  issue_status varchar(32) DEFAULT 'pending_dispatch' NOT NULL,
  indicator_id bigint DEFAULT NULL,
  indicator_name varchar(200) DEFAULT NULL,
  current_value numeric(20,4) DEFAULT NULL,
  threshold_value numeric(20,4) DEFAULT NULL,
  issue_description text DEFAULT NULL,
  rectification_result text DEFAULT NULL,
  review_opinion text DEFAULT NULL,
  attachment_url text DEFAULT NULL,
  dispatch_time timestamp DEFAULT NULL,
  submit_time timestamp DEFAULT NULL,
  review_time timestamp DEFAULT NULL,
  archive_time timestamp DEFAULT NULL,
  del_flag char(1) DEFAULT '0' NOT NULL,
  create_by varchar(64) DEFAULT '',
  create_time timestamp DEFAULT NULL,
  update_by varchar(64) DEFAULT '',
  update_time timestamp DEFAULT NULL,
  remark varchar(500) DEFAULT NULL,
  CONSTRAINT pk_nc_rectification_issue PRIMARY KEY (issue_id)
);

COMMENT ON TABLE nc_rectification_issue IS '问题整改台账';
COMMENT ON COLUMN nc_rectification_issue.issue_code IS '问题编号';
COMMENT ON COLUMN nc_rectification_issue.issue_title IS '问题标题';
COMMENT ON COLUMN nc_rectification_issue.source_type IS '来源类型（manual 人工新增，warning 预警转入）';
COMMENT ON COLUMN nc_rectification_issue.source_warning_id IS '来源预警 ID';
COMMENT ON COLUMN nc_rectification_issue.dept_id IS '所属部门 ID';
COMMENT ON COLUMN nc_rectification_issue.warning_level IS '预警级别';
COMMENT ON COLUMN nc_rectification_issue.region_name IS '地区';
COMMENT ON COLUMN nc_rectification_issue.responsible_unit_name IS '责任单位';
COMMENT ON COLUMN nc_rectification_issue.responsible_person IS '责任人';
COMMENT ON COLUMN nc_rectification_issue.supervisor_name IS '督办人';
COMMENT ON COLUMN nc_rectification_issue.deadline IS '整改期限';
COMMENT ON COLUMN nc_rectification_issue.issue_status IS '整改状态（pending_dispatch 待派发，pending_rectification 待整改，rectifying 整改中，pending_review 待复核，closed 已办结，rejected 已驳回，rework 重新整改，archived 已归档）';
COMMENT ON COLUMN nc_rectification_issue.current_value IS '当前值';
COMMENT ON COLUMN nc_rectification_issue.threshold_value IS '阈值';
COMMENT ON COLUMN nc_rectification_issue.issue_description IS '问题描述';
COMMENT ON COLUMN nc_rectification_issue.rectification_result IS '整改结果';
COMMENT ON COLUMN nc_rectification_issue.review_opinion IS '复核意见';
COMMENT ON COLUMN nc_rectification_issue.attachment_url IS '附件地址';
COMMENT ON COLUMN nc_rectification_issue.dispatch_time IS '派发时间';
COMMENT ON COLUMN nc_rectification_issue.submit_time IS '提交复核时间';
COMMENT ON COLUMN nc_rectification_issue.review_time IS '复核时间';
COMMENT ON COLUMN nc_rectification_issue.archive_time IS '归档时间';

CREATE INDEX IF NOT EXISTS idx_nc_rectification_issue_status ON nc_rectification_issue(issue_status);
CREATE INDEX IF NOT EXISTS idx_nc_rectification_issue_source_warning ON nc_rectification_issue(source_warning_id);
CREATE INDEX IF NOT EXISTS idx_nc_rectification_issue_dept_id ON nc_rectification_issue(dept_id);

-- ============================================================
-- 整改流程时间线
-- ============================================================
CREATE TABLE IF NOT EXISTS nc_rectification_log (
  log_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  issue_id bigint NOT NULL,
  from_status varchar(32) DEFAULT NULL,
  to_status varchar(32) DEFAULT NULL,
  action_name varchar(64) DEFAULT NULL,
  handle_by varchar(64) DEFAULT NULL,
  handle_time timestamp DEFAULT NULL,
  handle_opinion text DEFAULT NULL,
  del_flag char(1) DEFAULT '0' NOT NULL,
  create_by varchar(64) DEFAULT '',
  create_time timestamp DEFAULT NULL,
  remark varchar(500) DEFAULT NULL,
  CONSTRAINT pk_nc_rectification_log PRIMARY KEY (log_id)
);

COMMENT ON TABLE nc_rectification_log IS '问题整改流程时间线';
COMMENT ON COLUMN nc_rectification_log.issue_id IS '整改问题 ID';
COMMENT ON COLUMN nc_rectification_log.from_status IS '变更前状态';
COMMENT ON COLUMN nc_rectification_log.to_status IS '变更后状态';
COMMENT ON COLUMN nc_rectification_log.action_name IS '操作名称';
COMMENT ON COLUMN nc_rectification_log.handle_by IS '操作人';
COMMENT ON COLUMN nc_rectification_log.handle_time IS '操作时间';
COMMENT ON COLUMN nc_rectification_log.handle_opinion IS '处理意见';

CREATE INDEX IF NOT EXISTS idx_nc_rectification_log_issue_id ON nc_rectification_log(issue_id);

-- ============================================================
-- 问题整改菜单（nocontact 模块下）
-- ============================================================
INSERT INTO sys_menu (menu_id, menu_name, parent_id, order_num, path, component, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, remark)
VALUES (3300, '问题整改管理', 0, 4, 'rectification', '', 1, 0, 'M', '0', '0', '', 'documentation', 'admin', now(), '问题整改管理')
ON CONFLICT (menu_id) DO NOTHING;

INSERT INTO sys_menu (menu_id, menu_name, parent_id, order_num, path, component, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, remark)
VALUES (3310, '问题台账列表', 3300, 1, 'issue', 'nocontact/rectification/issue/index', 1, 0, 'C', '0', '0', 'nocontact:rectification:issue:list', 'list', 'admin', now(), '问题台账列表')
ON CONFLICT (menu_id) DO NOTHING;

INSERT INTO sys_menu (menu_id, menu_name, parent_id, order_num, path, component, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, remark)
VALUES (3311, '问题查询', 3310, 1, '', '', 1, 0, 'F', '0', '0', 'nocontact:rectification:issue:query', '#', 'admin', now(), '')
ON CONFLICT (menu_id) DO NOTHING;

INSERT INTO sys_menu (menu_id, menu_name, parent_id, order_num, path, component, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, remark)
VALUES (3312, '问题新增', 3310, 2, '', '', 1, 0, 'F', '0', '0', 'nocontact:rectification:issue:add', '#', 'admin', now(), '')
ON CONFLICT (menu_id) DO NOTHING;

INSERT INTO sys_menu (menu_id, menu_name, parent_id, order_num, path, component, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, remark)
VALUES (3313, '问题处理', 3310, 3, '', '', 1, 0, 'F', '0', '0', 'nocontact:rectification:issue:edit', '#', 'admin', now(), '')
ON CONFLICT (menu_id) DO NOTHING;

INSERT INTO sys_menu (menu_id, menu_name, parent_id, order_num, path, component, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, remark)
VALUES (3314, '问题删除', 3310, 4, '', '', 1, 0, 'F', '0', '0', 'nocontact:rectification:issue:remove', '#', 'admin', now(), '')
ON CONFLICT (menu_id) DO NOTHING;

INSERT INTO sys_menu (menu_id, menu_name, parent_id, order_num, path, component, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, remark)
VALUES (3320, '问题详情与处理流程', 3300, 2, 'detail', 'nocontact/rectification/detail/index', 1, 0, 'C', '0', '0', 'nocontact:rectification:issue:query', 'guide', 'admin', now(), '问题详情与处理流程')
ON CONFLICT (menu_id) DO NOTHING;

INSERT INTO sys_menu (menu_id, menu_name, parent_id, order_num, path, component, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, remark)
VALUES (3330, '整改跟踪看板', 3300, 3, 'dashboard', 'nocontact/rectification/dashboard/index', 1, 0, 'C', '0', '0', 'nocontact:rectification:issue:list', 'dashboard', 'admin', now(), '整改跟踪看板')
ON CONFLICT (menu_id) DO NOTHING;
