-- 营商无感业务模块 002：数据融合与监测预警 P0 闭环增量
-- 手工执行，幂等，不由服务启动自动迁移。

CREATE TABLE IF NOT EXISTS nc_fusion_collection_batch (
  batch_id bigint not null GENERATED BY DEFAULT AS IDENTITY,
  task_id bigint,
  batch_name varchar(160) not null,
  source_type varchar(24) default 'form',
  source_name varchar(160) default '',
  source_record_id varchar(120) default '',
  responsible_unit_id bigint,
  responsible_unit_name varchar(160) default '',
  region_code varchar(32) default '',
  region_name varchar(64) default '',
  period_type varchar(24) default 'month',
  period_year int,
  period_quarter int,
  period_month int,
  period_key varchar(32) not null,
  batch_status varchar(24) default 'draft',
  submit_by varchar(64) default '',
  submit_time timestamp,
  audit_by varchar(64) default '',
  audit_time timestamp,
  audit_opinion varchar(500) default '',
  item_count int default 0,
  del_flag char(1) default '0',
  create_by varchar(64) default '',
  create_time timestamp,
  update_by varchar(64) default '',
  update_time timestamp,
  remark varchar(500) default null,
  CONSTRAINT pk_nc_fusion_collection_batch PRIMARY KEY (batch_id)
);

COMMENT ON TABLE nc_fusion_collection_batch IS '数据采集批次';
COMMENT ON COLUMN nc_fusion_collection_batch.batch_status IS '状态（draft草稿 pending_audit待审核 approved已审核 rejected已驳回）';

CREATE TABLE IF NOT EXISTS nc_fusion_collection_item (
  item_id bigint not null GENERATED BY DEFAULT AS IDENTITY,
  batch_id bigint not null,
  indicator_id bigint not null,
  indicator_name varchar(200) default '',
  indicator_code varchar(80) default '',
  raw_value varchar(500) default '',
  value_decimal numeric(18,4),
  value_text varchar(500) default '',
  value_date timestamp,
  validation_status varchar(24) default 'valid',
  validation_message varchar(500) default '',
  is_current char(1) default '1',
  del_flag char(1) default '0',
  create_by varchar(64) default '',
  create_time timestamp,
  update_by varchar(64) default '',
  update_time timestamp,
  remark varchar(500) default null,
  CONSTRAINT pk_nc_fusion_collection_item PRIMARY KEY (item_id)
);

COMMENT ON TABLE nc_fusion_collection_item IS '数据采集明细';
COMMENT ON COLUMN nc_fusion_collection_item.validation_status IS '校验状态（valid有效 invalid无效）';

CREATE TABLE IF NOT EXISTS nc_fusion_collection_audit_log (
  log_id bigint not null GENERATED BY DEFAULT AS IDENTITY,
  batch_id bigint not null,
  from_status varchar(24) default '',
  to_status varchar(24) default '',
  action_name varchar(80) default '',
  audit_by varchar(64) default '',
  audit_time timestamp,
  audit_opinion varchar(500) default '',
  create_by varchar(64) default '',
  create_time timestamp,
  remark varchar(500) default null,
  CONSTRAINT pk_nc_fusion_collection_audit_log PRIMARY KEY (log_id)
);

COMMENT ON TABLE nc_fusion_collection_audit_log IS '数据采集审核日志';

CREATE TABLE IF NOT EXISTS nc_warning_message_handle_log (
  log_id bigint not null GENERATED BY DEFAULT AS IDENTITY,
  message_id bigint not null,
  from_status varchar(24) default '',
  to_status varchar(24) default '',
  handle_by varchar(64) default '',
  handle_time timestamp,
  handle_opinion varchar(500) default '',
  create_by varchar(64) default '',
  create_time timestamp,
  remark varchar(500) default null,
  CONSTRAINT pk_nc_warning_message_handle_log PRIMARY KEY (log_id)
);

COMMENT ON TABLE nc_warning_message_handle_log IS '预警消息处理日志';

ALTER TABLE nc_warning_rule ADD COLUMN IF NOT EXISTS threshold_value_max numeric(18,4);

ALTER TABLE nc_warning_message ADD COLUMN IF NOT EXISTS responsible_unit_id bigint;
ALTER TABLE nc_warning_message ADD COLUMN IF NOT EXISTS responsible_unit_name varchar(160) default '';
ALTER TABLE nc_warning_message ADD COLUMN IF NOT EXISTS region_code varchar(32) default '';
ALTER TABLE nc_warning_message ADD COLUMN IF NOT EXISTS period_key varchar(32) default '';
ALTER TABLE nc_warning_message ADD COLUMN IF NOT EXISTS business_key varchar(160) default '';
ALTER TABLE nc_warning_message ADD COLUMN IF NOT EXISTS hit_count int default 1;
ALTER TABLE nc_warning_message ADD COLUMN IF NOT EXISTS source_batch_id bigint;
ALTER TABLE nc_warning_message ADD COLUMN IF NOT EXISTS source_item_id bigint;
ALTER TABLE nc_warning_message ADD COLUMN IF NOT EXISTS latest_hit_time timestamp;
ALTER TABLE nc_warning_message ADD COLUMN IF NOT EXISTS handle_opinion varchar(500) default '';

ALTER TABLE nc_warning_message ALTER COLUMN message_status SET DEFAULT 'pending';

UPDATE nc_warning_message
SET message_status = 'pending'
WHERE message_status in ('sent', 'read');

UPDATE nc_warning_message
SET message_status = 'closed'
WHERE message_status = 'handled';

UPDATE nc_warning_message
SET message_status = 'ignored'
WHERE message_status = 'archived';

UPDATE nc_warning_message
SET latest_hit_time = trigger_time
WHERE latest_hit_time IS NULL;

UPDATE nc_warning_message
SET hit_count = 1
WHERE hit_count IS NULL;

UPDATE nc_warning_message
SET business_key = rule_id || ':' || indicator_id || ':' || coalesce(responsible_unit_id, 0) || ':' || coalesce(period_key, '')
WHERE business_key IS NULL OR business_key = '';

CREATE INDEX IF NOT EXISTS idx_nc_fusion_batch_status ON nc_fusion_collection_batch(batch_status);
CREATE INDEX IF NOT EXISTS idx_nc_fusion_batch_period ON nc_fusion_collection_batch(period_key);
CREATE INDEX IF NOT EXISTS idx_nc_fusion_batch_unit ON nc_fusion_collection_batch(responsible_unit_id);
CREATE INDEX IF NOT EXISTS idx_nc_fusion_item_batch ON nc_fusion_collection_item(batch_id);
CREATE INDEX IF NOT EXISTS idx_nc_fusion_item_indicator ON nc_fusion_collection_item(indicator_id);
CREATE INDEX IF NOT EXISTS idx_nc_fusion_audit_batch ON nc_fusion_collection_audit_log(batch_id);
CREATE INDEX IF NOT EXISTS idx_nc_warning_message_business ON nc_warning_message(business_key);
CREATE INDEX IF NOT EXISTS idx_nc_warning_message_period ON nc_warning_message(period_key);
CREATE INDEX IF NOT EXISTS idx_nc_warning_message_unit ON nc_warning_message(responsible_unit_id);
CREATE INDEX IF NOT EXISTS idx_nc_warning_handle_message ON nc_warning_message_handle_log(message_id);

-- 采集批次审核菜单
INSERT INTO sys_menu(menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark)
SELECT 3030, '采集批次审核', 3000, 3, 'collection', 'nocontact/fusion/collection/index', '', '', 1, 0, 'C', '0', '0', 'fusion:collection:list', 'form', 'admin', current_timestamp, '', NULL, '采集批次审核'
WHERE NOT EXISTS (SELECT 1 FROM sys_menu WHERE menu_id = 3030);

INSERT INTO sys_menu(menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark)
SELECT 3031, '采集批次查询', 3030, 1, '', '', '', '', 1, 0, 'F', '0', '0', 'fusion:collection:query', '#', 'admin', current_timestamp, '', NULL, ''
WHERE NOT EXISTS (SELECT 1 FROM sys_menu WHERE menu_id = 3031);

INSERT INTO sys_menu(menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark)
SELECT 3032, '采集批次提交', 3030, 2, '', '', '', '', 1, 0, 'F', '0', '0', 'fusion:collection:add', '#', 'admin', current_timestamp, '', NULL, ''
WHERE NOT EXISTS (SELECT 1 FROM sys_menu WHERE menu_id = 3032);

INSERT INTO sys_menu(menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark)
SELECT 3033, '采集批次审核', 3030, 3, '', '', '', '', 1, 0, 'F', '0', '0', 'fusion:collection:audit', '#', 'admin', current_timestamp, '', NULL, ''
WHERE NOT EXISTS (SELECT 1 FROM sys_menu WHERE menu_id = 3033);

INSERT INTO sys_menu(menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark)
SELECT 3223, '预警消息删除', 3220, 3, '', '', '', '', 1, 0, 'F', '0', '0', 'warning:message:remove', '#', 'admin', current_timestamp, '', NULL, ''
WHERE NOT EXISTS (SELECT 1 FROM sys_menu WHERE menu_id = 3223);
