DROP DATABASE IF EXISTS "ry-config";

CREATE DATABASE "ry-config";

/******************************************/
/*   表名称 = config_info   */
/******************************************/
CREATE TABLE "config_info" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "data_id" varchar(255) NOT NULL,
  "group_id" varchar(128) DEFAULT NULL,
  "content" text NOT NULL,
  "md5" varchar(32) DEFAULT NULL,
  "gmt_create" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "gmt_modified" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "src_user" text,
  "src_ip" varchar(50) DEFAULT NULL,
  "app_name" varchar(128) DEFAULT NULL,
  "tenant_id" varchar(128) DEFAULT '',
  "c_desc" varchar(256) DEFAULT NULL,
  "c_use" varchar(64) DEFAULT NULL,
  "effect" varchar(64) DEFAULT NULL,
  "type" varchar(64) DEFAULT NULL,
  "c_schema" text,
  "encrypted_data_key" varchar(1024) NOT NULL DEFAULT '',
  PRIMARY KEY ("id"),
  UNIQUE ("data_id","group_id","tenant_id")
);
COMMENT ON TABLE "config_info" IS 'config_info';
COMMENT ON COLUMN "config_info"."id" IS 'id';
COMMENT ON COLUMN "config_info"."data_id" IS 'data_id';
COMMENT ON COLUMN "config_info"."group_id" IS 'group_id';
COMMENT ON COLUMN "config_info"."content" IS 'content';
COMMENT ON COLUMN "config_info"."md5" IS 'md5';
COMMENT ON COLUMN "config_info"."gmt_create" IS '创建时间';
COMMENT ON COLUMN "config_info"."gmt_modified" IS '修改时间';
COMMENT ON COLUMN "config_info"."src_user" IS 'source user';
COMMENT ON COLUMN "config_info"."src_ip" IS 'source ip';
COMMENT ON COLUMN "config_info"."app_name" IS 'app_name';
COMMENT ON COLUMN "config_info"."tenant_id" IS '租户字段';
COMMENT ON COLUMN "config_info"."c_desc" IS 'configuration description';
COMMENT ON COLUMN "config_info"."c_use" IS 'configuration usage';
COMMENT ON COLUMN "config_info"."effect" IS '配置生效的描述';
COMMENT ON COLUMN "config_info"."type" IS '配置的类型';
COMMENT ON COLUMN "config_info"."c_schema" IS '配置的模式';
COMMENT ON COLUMN "config_info"."encrypted_data_key" IS '密钥';

insert into config_info(id, data_id, group_id, content, md5, gmt_create, gmt_modified, src_user, src_ip, app_name, tenant_id, c_desc, c_use, effect, type, c_schema, encrypted_data_key) values 
(1,'application-dev.yml','DEFAULT_GROUP','spring:\n  autoconfigure:\n    exclude: com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure\n\n# feign 配置\nfeign:\n  sentinel:\n    enabled: true\n  okhttp:\n    enabled: true\n  httpclient:\n    enabled: false\n  client:\n    config:\n      default:\n        connectTimeout: 10000\n        readTimeout: 10000\n  compression:\n    request:\n      enabled: true\n      min-request-size: 8192\n    response:\n      enabled: true\n\n# 暴露监控端点\nmanagement:\n  endpoints:\n    web:\n      exposure:\n        include: \'*\'\n','9928f41dfb10386ad38b3254af5692e0','2020-05-20 12:00:00','2024-08-29 12:14:45','nacos','0:0:0:0:0:0:0:1','','','通用配置','null','null','yaml','',''),
(2,'ruoyi-gateway-dev.yml','DEFAULT_GROUP','spring:\n  redis:\n    host: ${REDIS_HOST:localhost}\n    port: 6379\n    password: \n  cloud:\n    gateway:\n      discovery:\n        locator:\n          lowerCaseServiceId: true\n          enabled: true\n      routes:\n        # 认证中心\n        - id: ruoyi-auth\n          uri: lb://ruoyi-auth\n          predicates:\n            - Path=/auth/**\n          filters:\n            # 验证码处理\n            - CacheRequestBody\n            - ValidateCodeFilter\n            - StripPrefix=1\n        # 代码生成\n        - id: ruoyi-gen\n          uri: lb://ruoyi-gen\n          predicates:\n            - Path=/code/**\n          filters:\n            - StripPrefix=1\n        # 定时任务\n        - id: ruoyi-job\n          uri: lb://ruoyi-job\n          predicates:\n            - Path=/schedule/**\n          filters:\n            - StripPrefix=1\n        # 系统模块\n        - id: ruoyi-system\n          uri: lb://ruoyi-system\n          predicates:\n            - Path=/system/**\n          filters:\n            - StripPrefix=1\n        # 文件服务\n        - id: ruoyi-file\n          uri: lb://ruoyi-file\n          predicates:\n            - Path=/file/**\n          filters:\n            - StripPrefix=1\n\n# 安全配置\nsecurity:\n  # 验证码\n  captcha:\n    enabled: true\n    type: math\n  # 防止XSS攻击\n  xss:\n    enabled: true\n    excludeUrls:\n      - /system/notice\n\n  # 不校验白名单\n  ignore:\n    whites:\n      - /auth/logout\n      - /auth/login\n      - /auth/register\n      - /*/v2/api-docs\n      - /*/v3/api-docs\n      - /csrf\n\n# springdoc配置\nspringdoc:\n  webjars:\n    # 访问前缀\n    prefix:\n','4d329eb08a941a8dd9d26f542c6ac6c5','2020-05-14 14:17:55','2024-09-02 12:13:50','nacos','0:0:0:0:0:0:0:1','','','网关模块','null','null','yaml','',''),
(3,'ruoyi-auth-dev.yml','DEFAULT_GROUP','spring:\n  redis:\n    host: ${REDIS_HOST:localhost}\n    port: 6379\n    password: \n','a03e7632a0a74520eeb4fbedd6d82d97','2020-11-20 00:00:00','2024-09-02 12:13:58','nacos','0:0:0:0:0:0:0:1','','','认证中心','null','null','yaml','',''),
(4,'ruoyi-monitor-dev.yml','DEFAULT_GROUP','# spring\nspring:\n  security:\n    user:\n      name: ruoyi\n      password: 123456\n  boot:\n    admin:\n      ui:\n        title: 若依服务状态监控\n','6f122fd2bfb8d45f858e7d6529a9cd44','2020-11-20 00:00:00','2024-08-29 12:15:11','nacos','0:0:0:0:0:0:0:1','','','监控中心','null','null','yaml','',''),
(5,'ruoyi-system-dev.yml','DEFAULT_GROUP','# spring配置\nspring:\n  redis:\n    host: ${REDIS_HOST:localhost}\n    port: 6379\n    password: \n  datasource:\n    druid:\n      stat-view-servlet:\n        enabled: true\n        loginUsername: ruoyi\n        loginPassword: 123456\n    dynamic:\n      druid:\n        initial-size: 5\n        min-idle: 5\n        maxActive: 20\n        maxWait: 60000\n        connectTimeout: 30000\n        socketTimeout: 60000\n        timeBetweenEvictionRunsMillis: 60000\n        minEvictableIdleTimeMillis: 300000\n        validationQuery: SELECT 1\n        testWhileIdle: true\n        testOnBorrow: false\n        testOnReturn: false\n        poolPreparedStatements: true\n        maxPoolPreparedStatementPerConnectionSize: 20\n        filters: stat,slf4j\n        connectionProperties: druid.stat.mergeSql\\=true;druid.stat.slowSqlMillis\\=5000\n      datasource:\n          # 主库数据源\n          master:\n            driver-class-name: org.postgresql.Driver\n            url: jdbc:postgresql://${KINGBASE_HOST:localhost}:${KINGBASE_PORT:54321}/ry-cloud\n            username: ${KINGBASE_USERNAME:root}\n            password: ${KINGBASE_PASSWORD:password}\n          # 从库数据源\n          # slave:\n            # username: \n            # password: \n            # url: \n            # driver-class-name: \n\n# mybatis配置\nmybatis:\n    # 搜索指定包别名\n    typeAliasesPackage: com.ruoyi.system\n    # 配置mapper的扫描，找到所有的mapper.xml映射文件\n    mapperLocations: classpath:mapper/**/*.xml\n\n# springdoc配置\nspringdoc:\n  gatewayUrl: http://localhost:8080/${spring.application.name}\n  api-docs:\n    # 是否开启接口文档\n    enabled: true\n  info:\n    # 标题\n    title: \'系统模块接口文档\'\n    # 描述\n    description: \'系统模块接口描述\'\n    # 作者信息\n    contact:\n      name: RuoYi\n      url: https://ruoyi.vip\n','786c7daf4543411fc65c3e48dfb15243','2020-11-20 00:00:00','2024-09-02 12:14:33','nacos','0:0:0:0:0:0:0:1','','','系统模块','null','null','yaml','',''),
(6,'ruoyi-gen-dev.yml','DEFAULT_GROUP','# spring配置\nspring:\n  redis:\n    host: ${REDIS_HOST:localhost}\n    port: 6379\n    password: \n  datasource:\n    driver-class-name: org.postgresql.Driver\n    url: jdbc:postgresql://${KINGBASE_HOST:localhost}:${KINGBASE_PORT:54321}/ry-cloud\n    username: ${KINGBASE_USERNAME:root}\n    password: ${KINGBASE_PASSWORD:password}\n\n# mybatis配置\nmybatis:\n    # 搜索指定包别名\n    typeAliasesPackage: com.ruoyi.gen.domain\n    # 配置mapper的扫描，找到所有的mapper.xml映射文件\n    mapperLocations: classpath:mapper/**/*.xml\n\n# springdoc配置\nspringdoc:\n  gatewayUrl: http://localhost:8080/${spring.application.name}\n  api-docs:\n    # 是否开启接口文档\n    enabled: true\n  info:\n    # 标题\n    title: \'代码生成接口文档\'\n    # 描述\n    description: \'代码生成接口描述\'\n    # 作者信息\n    contact:\n      name: RuoYi\n      url: https://ruoyi.vip\n\n# 代码生成\ngen:\n  # 作者\n  author: ruoyi\n  # 默认生成包路径 system 需改成自己的模块名称 如 system monitor tool\n  packageName: com.ruoyi.system\n  # 自动去除表前缀，默认是false\n  autoRemovePre: false\n  # 表前缀（生成类名不会包含表前缀，多个用逗号分隔）\n  tablePrefix: sys_\n  # 是否允许生成文件覆盖到本地（自定义路径），默认不允许\n  allowOverwrite: false','43d807aa0a4accbb193b6dc7e38ac8a3','2020-11-20 00:00:00','2024-12-25 08:29:33','nacos','0:0:0:0:0:0:0:1','','','代码生成','null','null','yaml','',''),
(7,'ruoyi-job-dev.yml','DEFAULT_GROUP','# spring配置\nspring:\n  redis:\n    host: ${REDIS_HOST:localhost}\n    port: 6379\n    password: \n  datasource:\n    driver-class-name: org.postgresql.Driver\n    url: jdbc:postgresql://${KINGBASE_HOST:localhost}:${KINGBASE_PORT:54321}/ry-cloud\n    username: ${KINGBASE_USERNAME:root}\n    password: ${KINGBASE_PASSWORD:password}\n\n# mybatis配置\nmybatis:\n    # 搜索指定包别名\n    typeAliasesPackage: com.ruoyi.job.domain\n    # 配置mapper的扫描，找到所有的mapper.xml映射文件\n    mapperLocations: classpath:mapper/**/*.xml\n\n# springdoc配置\nspringdoc:\n  gatewayUrl: http://localhost:8080/${spring.application.name}\n  api-docs:\n    # 是否开启接口文档\n    enabled: true\n  info:\n    # 标题\n    title: \'定时任务接口文档\'\n    # 描述\n    description: \'定时任务接口描述\'\n    # 作者信息\n    contact:\n      name: RuoYi\n      url: https://ruoyi.vip\n','f78483f845777335b9ed4a9f84758848','2020-11-20 00:00:00','2024-09-02 12:14:56','nacos','0:0:0:0:0:0:0:1','','','定时任务','null','null','yaml','',''),
(8,'ruoyi-file-dev.yml','DEFAULT_GROUP','# 本地文件上传    \nfile:\n    domain: http://127.0.0.1:9300\n    path: D:/ruoyi/uploadPath\n    prefix: /statics\n\n# FastDFS配置\nfdfs:\n  domain: http://127.0.0.1\n  soTimeout: 3000\n  connectTimeout: 2000\n  trackerList: 127.0.0.1:22122\n\n# Minio配置\nminio:\n  url: http://127.0.0.1:9000\n  accessKey: minioadmin\n  secretKey: minioadmin\n  bucketName: test\n\n  # 防盗链配置\nreferer:\n  # 防盗链开关\n  enabled: false\n  # 允许的域名列表\n  allowed-domains: localhost,127.0.0.1,ruoyi.vip,www.ruoyi.vip\n','095791a04211d6e3d294359b21357394','2020-11-20 00:00:00','2025-09-02 05:10:11','nacos','0:0:0:0:0:0:0:1','','','文件服务','null','null','yaml','',''),
(9,'sentinel-ruoyi-gateway','DEFAULT_GROUP','[\r\n    {\r\n        \"resource\": \"ruoyi-auth\",\r\n        \"count\": 500,\r\n        \"grade\": 1,\r\n        \"limitApp\": \"default\",\r\n        \"strategy\": 0,\r\n        \"controlBehavior\": 0\r\n    },\r\n	{\r\n        \"resource\": \"ruoyi-system\",\r\n        \"count\": 1000,\r\n        \"grade\": 1,\r\n        \"limitApp\": \"default\",\r\n        \"strategy\": 0,\r\n        \"controlBehavior\": 0\r\n    },\r\n	{\r\n        \"resource\": \"ruoyi-gen\",\r\n        \"count\": 200,\r\n        \"grade\": 1,\r\n        \"limitApp\": \"default\",\r\n        \"strategy\": 0,\r\n        \"controlBehavior\": 0\r\n    },\r\n	{\r\n        \"resource\": \"ruoyi-job\",\r\n        \"count\": 300,\r\n        \"grade\": 1,\r\n        \"limitApp\": \"default\",\r\n        \"strategy\": 0,\r\n        \"controlBehavior\": 0\r\n    }\r\n]','9f3a3069261598f74220bc47958ec252','2020-11-20 00:00:00','2020-11-20 00:00:00',NULL,'0:0:0:0:0:0:0:1','','','限流策略','null','null','json',NULL,'');

/******************************************/
/*   表名称 = config_info_aggr   */
/******************************************/
CREATE TABLE "config_info_aggr" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "data_id" varchar(255) NOT NULL,
  "group_id" varchar(255) NOT NULL,
  "datum_id" varchar(255) NOT NULL,
  "content" text NOT NULL,
  "gmt_modified" timestamp NOT NULL,
  "app_name" varchar(128) DEFAULT NULL,
  "tenant_id" varchar(128) DEFAULT '',
  PRIMARY KEY ("id"),
  UNIQUE ("data_id","group_id","tenant_id","datum_id")
);
COMMENT ON TABLE "config_info_aggr" IS '增加租户字段';
COMMENT ON COLUMN "config_info_aggr"."id" IS 'id';
COMMENT ON COLUMN "config_info_aggr"."data_id" IS 'data_id';
COMMENT ON COLUMN "config_info_aggr"."group_id" IS 'group_id';
COMMENT ON COLUMN "config_info_aggr"."datum_id" IS 'datum_id';
COMMENT ON COLUMN "config_info_aggr"."content" IS '内容';
COMMENT ON COLUMN "config_info_aggr"."gmt_modified" IS '修改时间';
COMMENT ON COLUMN "config_info_aggr"."tenant_id" IS '租户字段';

/******************************************/
/*   表名称 = config_info  since 2.5.0    */
/******************************************/
CREATE TABLE "config_info_gray" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "data_id" varchar(255) NOT NULL,
  "group_id" varchar(128) NOT NULL,
  "content" text NOT NULL,
  "md5" varchar(32) DEFAULT NULL,
  "src_user" text,
  "src_ip" varchar(100) DEFAULT NULL,
  "gmt_create" timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  "gmt_modified" timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  "app_name" varchar(128) DEFAULT NULL,
  "tenant_id" varchar(128) DEFAULT '',
  "gray_name" varchar(128) NOT NULL,
  "gray_rule" text NOT NULL,
  "encrypted_data_key" varchar(256) NOT NULL DEFAULT '',
  PRIMARY KEY ("id"),
  UNIQUE ("data_id","group_id","tenant_id","gray_name"));
COMMENT ON TABLE "config_info_gray" IS 'config_info_gray';
COMMENT ON COLUMN "config_info_gray"."id" IS 'id';
COMMENT ON COLUMN "config_info_gray"."data_id" IS 'data_id';
COMMENT ON COLUMN "config_info_gray"."group_id" IS 'group_id';
COMMENT ON COLUMN "config_info_gray"."content" IS 'content';
COMMENT ON COLUMN "config_info_gray"."md5" IS 'md5';
COMMENT ON COLUMN "config_info_gray"."src_user" IS 'src_user';
COMMENT ON COLUMN "config_info_gray"."src_ip" IS 'src_ip';
COMMENT ON COLUMN "config_info_gray"."gmt_create" IS 'gmt_create';
COMMENT ON COLUMN "config_info_gray"."gmt_modified" IS 'gmt_modified';
COMMENT ON COLUMN "config_info_gray"."app_name" IS 'app_name';
COMMENT ON COLUMN "config_info_gray"."tenant_id" IS 'tenant_id';
COMMENT ON COLUMN "config_info_gray"."gray_name" IS 'gray_name';
COMMENT ON COLUMN "config_info_gray"."gray_rule" IS 'gray_rule';
COMMENT ON COLUMN "config_info_gray"."encrypted_data_key" IS 'encrypted_data_key';
CREATE INDEX "idx_dataid_gmt_modified" ON "config_info_gray" ("data_id","gmt_modified");
CREATE INDEX "idx_gmt_modified" ON "config_info_gray" ("gmt_modified");

/******************************************/
/*   表名称 = config_info_beta   */
/******************************************/
CREATE TABLE "config_info_beta" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "data_id" varchar(255) NOT NULL,
  "group_id" varchar(128) NOT NULL,
  "app_name" varchar(128) DEFAULT NULL,
  "content" text NOT NULL,
  "beta_ips" varchar(1024) DEFAULT NULL,
  "md5" varchar(32) DEFAULT NULL,
  "gmt_create" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "gmt_modified" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "src_user" text,
  "src_ip" varchar(50) DEFAULT NULL,
  "tenant_id" varchar(128) DEFAULT '',
  "encrypted_data_key" varchar(1024) NOT NULL DEFAULT '',
  PRIMARY KEY ("id"),
  UNIQUE ("data_id","group_id","tenant_id")
);
COMMENT ON TABLE "config_info_beta" IS 'config_info_beta';
COMMENT ON COLUMN "config_info_beta"."id" IS 'id';
COMMENT ON COLUMN "config_info_beta"."data_id" IS 'data_id';
COMMENT ON COLUMN "config_info_beta"."group_id" IS 'group_id';
COMMENT ON COLUMN "config_info_beta"."app_name" IS 'app_name';
COMMENT ON COLUMN "config_info_beta"."content" IS 'content';
COMMENT ON COLUMN "config_info_beta"."beta_ips" IS 'betaIps';
COMMENT ON COLUMN "config_info_beta"."md5" IS 'md5';
COMMENT ON COLUMN "config_info_beta"."gmt_create" IS '创建时间';
COMMENT ON COLUMN "config_info_beta"."gmt_modified" IS '修改时间';
COMMENT ON COLUMN "config_info_beta"."src_user" IS 'source user';
COMMENT ON COLUMN "config_info_beta"."src_ip" IS 'source ip';
COMMENT ON COLUMN "config_info_beta"."tenant_id" IS '租户字段';
COMMENT ON COLUMN "config_info_beta"."encrypted_data_key" IS '密钥';

/******************************************/
/*   表名称 = config_info_tag   */
/******************************************/
CREATE TABLE "config_info_tag" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "data_id" varchar(255) NOT NULL,
  "group_id" varchar(128) NOT NULL,
  "tenant_id" varchar(128) DEFAULT '',
  "tag_id" varchar(128) NOT NULL,
  "app_name" varchar(128) DEFAULT NULL,
  "content" text NOT NULL,
  "md5" varchar(32) DEFAULT NULL,
  "gmt_create" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "gmt_modified" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "src_user" text,
  "src_ip" varchar(50) DEFAULT NULL,
  PRIMARY KEY ("id"),
  UNIQUE ("data_id","group_id","tenant_id","tag_id")
);
COMMENT ON TABLE "config_info_tag" IS 'config_info_tag';
COMMENT ON COLUMN "config_info_tag"."id" IS 'id';
COMMENT ON COLUMN "config_info_tag"."data_id" IS 'data_id';
COMMENT ON COLUMN "config_info_tag"."group_id" IS 'group_id';
COMMENT ON COLUMN "config_info_tag"."tenant_id" IS 'tenant_id';
COMMENT ON COLUMN "config_info_tag"."tag_id" IS 'tag_id';
COMMENT ON COLUMN "config_info_tag"."app_name" IS 'app_name';
COMMENT ON COLUMN "config_info_tag"."content" IS 'content';
COMMENT ON COLUMN "config_info_tag"."md5" IS 'md5';
COMMENT ON COLUMN "config_info_tag"."gmt_create" IS '创建时间';
COMMENT ON COLUMN "config_info_tag"."gmt_modified" IS '修改时间';
COMMENT ON COLUMN "config_info_tag"."src_user" IS 'source user';
COMMENT ON COLUMN "config_info_tag"."src_ip" IS 'source ip';

/******************************************/
/*   表名称 = config_tags_relation   */
/******************************************/
CREATE TABLE "config_tags_relation" (
  "id" bigint NOT NULL,
  "tag_name" varchar(128) NOT NULL,
  "tag_type" varchar(64) DEFAULT NULL,
  "data_id" varchar(255) NOT NULL,
  "group_id" varchar(128) NOT NULL,
  "tenant_id" varchar(128) DEFAULT '',
  "nid" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  PRIMARY KEY ("nid"),
  UNIQUE ("id","tag_name","tag_type"));
COMMENT ON TABLE "config_tags_relation" IS 'config_tag_relation';
COMMENT ON COLUMN "config_tags_relation"."id" IS 'id';
COMMENT ON COLUMN "config_tags_relation"."tag_name" IS 'tag_name';
COMMENT ON COLUMN "config_tags_relation"."tag_type" IS 'tag_type';
COMMENT ON COLUMN "config_tags_relation"."data_id" IS 'data_id';
COMMENT ON COLUMN "config_tags_relation"."group_id" IS 'group_id';
COMMENT ON COLUMN "config_tags_relation"."tenant_id" IS 'tenant_id';
COMMENT ON COLUMN "config_tags_relation"."nid" IS 'nid, 自增长标识';
CREATE INDEX "idx_tenant_id" ON "config_tags_relation" ("tenant_id");

/******************************************/
/*   表名称 = group_capacity   */
/******************************************/
CREATE TABLE "group_capacity" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "group_id" varchar(128) NOT NULL DEFAULT '',
  "quota" int NOT NULL DEFAULT '0',
  "usage" int NOT NULL DEFAULT '0',
  "max_size" int NOT NULL DEFAULT '0',
  "max_aggr_count" int NOT NULL DEFAULT '0',
  "max_aggr_size" int NOT NULL DEFAULT '0',
  "max_history_count" int NOT NULL DEFAULT '0',
  "gmt_create" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "gmt_modified" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id"),
  UNIQUE ("group_id")
);
COMMENT ON TABLE "group_capacity" IS '集群、各Group容量信息表';
COMMENT ON COLUMN "group_capacity"."id" IS '主键ID';
COMMENT ON COLUMN "group_capacity"."group_id" IS 'Group ID，空字符表示整个集群';
COMMENT ON COLUMN "group_capacity"."quota" IS '配额，0表示使用默认值';
COMMENT ON COLUMN "group_capacity"."usage" IS '使用量';
COMMENT ON COLUMN "group_capacity"."max_size" IS '单个配置大小上限，单位为字节，0表示使用默认值';
COMMENT ON COLUMN "group_capacity"."max_aggr_count" IS '聚合子配置最大个数，，0表示使用默认值';
COMMENT ON COLUMN "group_capacity"."max_aggr_size" IS '单个聚合数据的子配置大小上限，单位为字节，0表示使用默认值';
COMMENT ON COLUMN "group_capacity"."max_history_count" IS '最大变更历史数量';
COMMENT ON COLUMN "group_capacity"."gmt_create" IS '创建时间';
COMMENT ON COLUMN "group_capacity"."gmt_modified" IS '修改时间';

/******************************************/
/*   表名称 = his_config_info   */
/******************************************/
CREATE TABLE "his_config_info" (
  "id" bigint NOT NULL,
  "nid" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "data_id" varchar(255) NOT NULL,
  "group_id" varchar(128) NOT NULL,
  "app_name" varchar(128) DEFAULT NULL,
  "content" text NOT NULL,
  "md5" varchar(32) DEFAULT NULL,
  "gmt_create" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "gmt_modified" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "src_user" text,
  "src_ip" varchar(50) DEFAULT NULL,
  "op_type" char(10) DEFAULT NULL,
  "tenant_id" varchar(128) DEFAULT '',
  "encrypted_data_key" varchar(1024) NOT NULL DEFAULT '',
  "publish_type" varchar(50)  DEFAULT 'formal',
  "gray_name" varchar(50)  DEFAULT NULL,
  "ext_info" text DEFAULT NULL,
  PRIMARY KEY ("nid")
);
COMMENT ON TABLE "his_config_info" IS '多租户改造';
COMMENT ON COLUMN "his_config_info"."id" IS 'id';
COMMENT ON COLUMN "his_config_info"."nid" IS 'nid, 自增标识';
COMMENT ON COLUMN "his_config_info"."data_id" IS 'data_id';
COMMENT ON COLUMN "his_config_info"."group_id" IS 'group_id';
COMMENT ON COLUMN "his_config_info"."app_name" IS 'app_name';
COMMENT ON COLUMN "his_config_info"."content" IS 'content';
COMMENT ON COLUMN "his_config_info"."md5" IS 'md5';
COMMENT ON COLUMN "his_config_info"."gmt_create" IS '创建时间';
COMMENT ON COLUMN "his_config_info"."gmt_modified" IS '修改时间';
COMMENT ON COLUMN "his_config_info"."src_user" IS 'source user';
COMMENT ON COLUMN "his_config_info"."src_ip" IS 'source ip';
COMMENT ON COLUMN "his_config_info"."op_type" IS 'operation type';
COMMENT ON COLUMN "his_config_info"."tenant_id" IS '租户字段';
COMMENT ON COLUMN "his_config_info"."encrypted_data_key" IS '密钥';
COMMENT ON COLUMN "his_config_info"."publish_type" IS 'publish type gray or formal';
COMMENT ON COLUMN "his_config_info"."gray_name" IS 'gray name';
COMMENT ON COLUMN "his_config_info"."ext_info" IS 'ext info';
CREATE INDEX "idx_gmt_create" ON "his_config_info" ("gmt_create");
CREATE INDEX "idx_gmt_modified" ON "his_config_info" ("gmt_modified");
CREATE INDEX "idx_did" ON "his_config_info" ("data_id");

/******************************************/
/*   数据库全名 = nacos_config   */
/*   表名称 = tenant_capacity   */
/******************************************/
CREATE TABLE "tenant_capacity" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "tenant_id" varchar(128) NOT NULL DEFAULT '',
  "quota" int NOT NULL DEFAULT '0',
  "usage" int NOT NULL DEFAULT '0',
  "max_size" int NOT NULL DEFAULT '0',
  "max_aggr_count" int NOT NULL DEFAULT '0',
  "max_aggr_size" int NOT NULL DEFAULT '0',
  "max_history_count" int NOT NULL DEFAULT '0',
  "gmt_create" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "gmt_modified" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id"),
  UNIQUE ("tenant_id")
);
COMMENT ON TABLE "tenant_capacity" IS '租户容量信息表';
COMMENT ON COLUMN "tenant_capacity"."id" IS '主键ID';
COMMENT ON COLUMN "tenant_capacity"."tenant_id" IS 'Tenant ID';
COMMENT ON COLUMN "tenant_capacity"."quota" IS '配额，0表示使用默认值';
COMMENT ON COLUMN "tenant_capacity"."usage" IS '使用量';
COMMENT ON COLUMN "tenant_capacity"."max_size" IS '单个配置大小上限，单位为字节，0表示使用默认值';
COMMENT ON COLUMN "tenant_capacity"."max_aggr_count" IS '聚合子配置最大个数';
COMMENT ON COLUMN "tenant_capacity"."max_aggr_size" IS '单个聚合数据的子配置大小上限，单位为字节，0表示使用默认值';
COMMENT ON COLUMN "tenant_capacity"."max_history_count" IS '最大变更历史数量';
COMMENT ON COLUMN "tenant_capacity"."gmt_create" IS '创建时间';
COMMENT ON COLUMN "tenant_capacity"."gmt_modified" IS '修改时间';

CREATE TABLE "tenant_info" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "kp" varchar(128) NOT NULL,
  "tenant_id" varchar(128) default '',
  "tenant_name" varchar(128) default '',
  "tenant_desc" varchar(256) DEFAULT NULL,
  "create_source" varchar(32) DEFAULT NULL,
  "gmt_create" bigint NOT NULL,
  "gmt_modified" bigint NOT NULL,
  PRIMARY KEY ("id"),
  UNIQUE ("kp","tenant_id"));
COMMENT ON TABLE "tenant_info" IS 'tenant_info';
COMMENT ON COLUMN "tenant_info"."id" IS 'id';
COMMENT ON COLUMN "tenant_info"."kp" IS 'kp';
COMMENT ON COLUMN "tenant_info"."tenant_id" IS 'tenant_id';
COMMENT ON COLUMN "tenant_info"."tenant_name" IS 'tenant_name';
COMMENT ON COLUMN "tenant_info"."tenant_desc" IS 'tenant_desc';
COMMENT ON COLUMN "tenant_info"."create_source" IS 'create_source';
COMMENT ON COLUMN "tenant_info"."gmt_create" IS '创建时间';
COMMENT ON COLUMN "tenant_info"."gmt_modified" IS '修改时间';
CREATE INDEX "idx_tenant_id" ON "tenant_info" ("tenant_id");

CREATE TABLE "users" (
  "username" varchar(50) NOT NULL PRIMARY KEY,
  "password" varchar(500) NOT NULL,
  "enabled" boolean NOT NULL
);
COMMENT ON COLUMN "users"."username" IS 'username';
COMMENT ON COLUMN "users"."password" IS 'password';
COMMENT ON COLUMN "users"."enabled" IS 'enabled';

CREATE TABLE "roles" (
  "username" varchar(50) NOT NULL,
  "role" varchar(50) NOT NULL,
  UNIQUE INDEX "idx_user_role" ("username" ASC, "role" ASC) USING BTREE
);
COMMENT ON COLUMN "roles"."username" IS 'username';
COMMENT ON COLUMN "roles"."role" IS 'role';

CREATE TABLE "permissions" (
  "role" varchar(50) NOT NULL,
  "resource" varchar(128) NOT NULL,
  "action" varchar(8) NOT NULL,
  UNIQUE INDEX "uk_role_permission" ("role","resource","action") "USING" BTREE
);
COMMENT ON COLUMN "permissions"."role" IS 'role';
COMMENT ON COLUMN "permissions"."resource" IS 'resource';
COMMENT ON COLUMN "permissions"."action" IS 'action';

INSERT INTO users (username, password, enabled) VALUES ('nacos', '$2a$10$EuWPZHzz32dJN7jexM34MOeYirDdFAZm2kuWj7VEOJhhZkDrxfvUu', TRUE);

INSERT INTO roles (username, role) VALUES ('nacos', 'ROLE_ADMIN');
