-- 问卷模块 003：问卷配置式设计器和版本发布

CREATE TABLE IF NOT EXISTS survey_questionnaire (
  questionnaire_id bigint not null GENERATED BY DEFAULT AS IDENTITY,
  questionnaire_name varchar(120) not null,
  description varchar(500) default '',
  status char(1) default '0',
  version_no int default 1,
  source_questionnaire_id bigint,
  published_time timestamp,
  ended_time timestamp,
  del_flag char(1) default '0',
  create_by varchar(64) default '',
  create_time timestamp,
  update_by varchar(64) default '',
  update_time timestamp,
  remark varchar(500) default null,
  CONSTRAINT pk_survey_questionnaire PRIMARY KEY (questionnaire_id)
);

COMMENT ON TABLE survey_questionnaire IS '问卷配置';
COMMENT ON COLUMN survey_questionnaire.questionnaire_id IS '问卷ID';
COMMENT ON COLUMN survey_questionnaire.questionnaire_name IS '问卷名称';
COMMENT ON COLUMN survey_questionnaire.status IS '状态（0草稿 1已发布 2已结束）';
COMMENT ON COLUMN survey_questionnaire.version_no IS '版本号';
COMMENT ON COLUMN survey_questionnaire.source_questionnaire_id IS '来源问卷ID';
COMMENT ON COLUMN survey_questionnaire.del_flag IS '删除标志（0代表存在 2代表删除）';

CREATE TABLE IF NOT EXISTS survey_question (
  question_id bigint not null GENERATED BY DEFAULT AS IDENTITY,
  questionnaire_id bigint not null,
  question_title varchar(300) not null,
  question_type varchar(32) not null,
  required_flag char(1) default '0',
  dimension varchar(80) default '',
  score_max int default 0,
  order_num int default 0,
  del_flag char(1) default '0',
  CONSTRAINT pk_survey_question PRIMARY KEY (question_id)
);

COMMENT ON TABLE survey_question IS '问卷题目';
COMMENT ON COLUMN survey_question.questionnaire_id IS '问卷ID';
COMMENT ON COLUMN survey_question.question_type IS '题型（single multiple text score matrix_score likert）';
COMMENT ON COLUMN survey_question.required_flag IS '是否必填（0否 1是）';
COMMENT ON COLUMN survey_question.dimension IS '题目维度';
COMMENT ON COLUMN survey_question.score_max IS '评分上限';

CREATE TABLE IF NOT EXISTS survey_question_option (
  option_id bigint not null GENERATED BY DEFAULT AS IDENTITY,
  question_id bigint not null,
  option_type varchar(16) default 'option',
  option_label varchar(200) not null,
  option_value varchar(100) default '',
  score_value int,
  order_num int default 0,
  CONSTRAINT pk_survey_question_option PRIMARY KEY (option_id)
);

COMMENT ON TABLE survey_question_option IS '问卷题目选项';
COMMENT ON COLUMN survey_question_option.question_id IS '题目ID';
COMMENT ON COLUMN survey_question_option.option_type IS '选项类型（option普通选项 row矩阵行 column矩阵列）';
COMMENT ON COLUMN survey_question_option.score_value IS '分值';

CREATE INDEX IF NOT EXISTS idx_survey_questionnaire_source ON survey_questionnaire(source_questionnaire_id);
CREATE INDEX IF NOT EXISTS idx_survey_question_questionnaire ON survey_question(questionnaire_id);
CREATE INDEX IF NOT EXISTS idx_survey_question_option_question ON survey_question_option(question_id);

-- 问卷管理菜单和按钮权限
INSERT INTO sys_menu(menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark)
SELECT 2000, '问卷调研', 0, 5, 'survey', NULL, '', '', 1, 0, 'M', '0', '0', '', 'form', 'admin', current_timestamp, '', NULL, '问卷调研目录'
WHERE NOT EXISTS (SELECT 1 FROM sys_menu WHERE menu_id = 2000);

INSERT INTO sys_menu(menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark)
SELECT 2020, '问卷管理', 2000, 2, 'questionnaire', 'survey/questionnaire/index', '', '', 1, 0, 'C', '0', '0', 'survey:questionnaire:list', 'form', 'admin', current_timestamp, '', NULL, '问卷管理菜单'
WHERE NOT EXISTS (SELECT 1 FROM sys_menu WHERE menu_id = 2020);

INSERT INTO sys_menu(menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark)
SELECT 2021, '问卷查询', 2020, 1, '', '', '', '', 1, 0, 'F', '0', '0', 'survey:questionnaire:query', '#', 'admin', current_timestamp, '', NULL, ''
WHERE NOT EXISTS (SELECT 1 FROM sys_menu WHERE menu_id = 2021);

INSERT INTO sys_menu(menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark)
SELECT 2022, '问卷新增', 2020, 2, '', '', '', '', 1, 0, 'F', '0', '0', 'survey:questionnaire:add', '#', 'admin', current_timestamp, '', NULL, ''
WHERE NOT EXISTS (SELECT 1 FROM sys_menu WHERE menu_id = 2022);

INSERT INTO sys_menu(menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark)
SELECT 2023, '问卷修改', 2020, 3, '', '', '', '', 1, 0, 'F', '0', '0', 'survey:questionnaire:edit', '#', 'admin', current_timestamp, '', NULL, ''
WHERE NOT EXISTS (SELECT 1 FROM sys_menu WHERE menu_id = 2023);

INSERT INTO sys_menu(menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark)
SELECT 2024, '问卷删除', 2020, 4, '', '', '', '', 1, 0, 'F', '0', '0', 'survey:questionnaire:remove', '#', 'admin', current_timestamp, '', NULL, ''
WHERE NOT EXISTS (SELECT 1 FROM sys_menu WHERE menu_id = 2024);

INSERT INTO sys_menu(menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark)
SELECT 2025, '问卷发布', 2020, 5, '', '', '', '', 1, 0, 'F', '0', '0', 'survey:questionnaire:publish', '#', 'admin', current_timestamp, '', NULL, ''
WHERE NOT EXISTS (SELECT 1 FROM sys_menu WHERE menu_id = 2025);

INSERT INTO sys_menu(menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark)
SELECT 2026, '问卷结束', 2020, 6, '', '', '', '', 1, 0, 'F', '0', '0', 'survey:questionnaire:end', '#', 'admin', current_timestamp, '', NULL, ''
WHERE NOT EXISTS (SELECT 1 FROM sys_menu WHERE menu_id = 2026);

INSERT INTO sys_menu(menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark)
SELECT 2027, '问卷列表', 2020, 7, '', '', '', '', 1, 0, 'F', '0', '0', 'survey:questionnaire:list', '#', 'admin', current_timestamp, '', NULL, ''
WHERE NOT EXISTS (SELECT 1 FROM sys_menu WHERE menu_id = 2027);
