-- 问卷模块 005：公开 token 填报页答卷

CREATE TABLE IF NOT EXISTS survey_response (
  response_id bigint not null GENERATED BY DEFAULT AS IDENTITY,
  task_id bigint not null,
  sample_id bigint not null,
  enterprise_id bigint not null,
  questionnaire_id bigint not null,
  submit_time timestamp not null,
  client_ip varchar(64) default '',
  status char(1) default '0',
  create_time timestamp,
  CONSTRAINT pk_survey_response PRIMARY KEY (response_id),
  CONSTRAINT uk_survey_response_sample UNIQUE (sample_id)
);

COMMENT ON TABLE survey_response IS '问卷答卷';
COMMENT ON COLUMN survey_response.task_id IS '调研任务ID';
COMMENT ON COLUMN survey_response.sample_id IS '任务样本ID';
COMMENT ON COLUMN survey_response.enterprise_id IS '企业ID';
COMMENT ON COLUMN survey_response.questionnaire_id IS '问卷版本ID';
COMMENT ON COLUMN survey_response.status IS '状态（0有效）';

CREATE TABLE IF NOT EXISTS survey_response_answer (
  answer_id bigint not null GENERATED BY DEFAULT AS IDENTITY,
  response_id bigint not null,
  question_id bigint not null,
  question_type varchar(32) not null,
  answer_text varchar(2000) default '',
  option_value varchar(500) default '',
  score_value int,
  CONSTRAINT pk_survey_response_answer PRIMARY KEY (answer_id)
);

COMMENT ON TABLE survey_response_answer IS '问卷答案明细';
COMMENT ON COLUMN survey_response_answer.response_id IS '答卷ID';
COMMENT ON COLUMN survey_response_answer.question_id IS '题目ID';
COMMENT ON COLUMN survey_response_answer.answer_text IS '文本、多选或矩阵答案';
COMMENT ON COLUMN survey_response_answer.option_value IS '单选或量表选项值';
COMMENT ON COLUMN survey_response_answer.score_value IS '评分值';

CREATE INDEX IF NOT EXISTS idx_survey_response_task ON survey_response(task_id);
CREATE INDEX IF NOT EXISTS idx_survey_response_enterprise ON survey_response(enterprise_id);
CREATE INDEX IF NOT EXISTS idx_survey_response_answer_response ON survey_response_answer(response_id);
