-- 问卷模块 002：企业库管理

CREATE TABLE IF NOT EXISTS survey_enterprise (
  enterprise_id bigint not null GENERATED BY DEFAULT AS IDENTITY,
  enterprise_name varchar(120) not null,
  credit_code varchar(18) not null,
  industry_category varchar(64) default '',
  region_code varchar(32) default '',
  region_name varchar(64) default '',
  enterprise_scale varchar(32) default '',
  contact_name varchar(30) default '',
  contact_phone varchar(20) default '',
  status char(1) default '0',
  del_flag char(1) default '0',
  create_by varchar(64) default '',
  create_time timestamp,
  update_by varchar(64) default '',
  update_time timestamp,
  remark varchar(500) default null,
  CONSTRAINT pk_survey_enterprise PRIMARY KEY (enterprise_id),
  CONSTRAINT uk_survey_enterprise_credit_code UNIQUE (credit_code)
);

COMMENT ON TABLE survey_enterprise IS '问卷企业库';
COMMENT ON COLUMN survey_enterprise.enterprise_id IS '企业ID';
COMMENT ON COLUMN survey_enterprise.enterprise_name IS '企业名称';
COMMENT ON COLUMN survey_enterprise.credit_code IS '统一社会信用代码';
COMMENT ON COLUMN survey_enterprise.industry_category IS '行业分类';
COMMENT ON COLUMN survey_enterprise.region_code IS '城市编码';
COMMENT ON COLUMN survey_enterprise.region_name IS '城市名称';
COMMENT ON COLUMN survey_enterprise.enterprise_scale IS '企业规模';
COMMENT ON COLUMN survey_enterprise.contact_name IS '联系人';
COMMENT ON COLUMN survey_enterprise.contact_phone IS '联系电话';
COMMENT ON COLUMN survey_enterprise.status IS '状态（0正常 1停用）';
COMMENT ON COLUMN survey_enterprise.del_flag IS '删除标志（0代表存在 2代表删除）';

CREATE TABLE IF NOT EXISTS survey_enterprise_group (
  group_id bigint not null GENERATED BY DEFAULT AS IDENTITY,
  parent_id bigint default 0,
  ancestors varchar(200) default '',
  group_name varchar(80) not null,
  order_num int default 0,
  status char(1) default '0',
  del_flag char(1) default '0',
  create_by varchar(64) default '',
  create_time timestamp,
  update_by varchar(64) default '',
  update_time timestamp,
  remark varchar(500) default null,
  CONSTRAINT pk_survey_enterprise_group PRIMARY KEY (group_id)
);

ALTER TABLE survey_enterprise_group ADD COLUMN IF NOT EXISTS del_flag char(1) default '0';

COMMENT ON TABLE survey_enterprise_group IS '问卷企业分组';
COMMENT ON COLUMN survey_enterprise_group.group_id IS '分组ID';
COMMENT ON COLUMN survey_enterprise_group.parent_id IS '父分组ID';
COMMENT ON COLUMN survey_enterprise_group.ancestors IS '祖级列表';
COMMENT ON COLUMN survey_enterprise_group.group_name IS '分组名称';
COMMENT ON COLUMN survey_enterprise_group.del_flag IS '删除标志（0代表存在 2代表删除）';

CREATE TABLE IF NOT EXISTS survey_enterprise_group_rel (
  enterprise_id bigint not null,
  group_id bigint not null,
  create_by varchar(64) default '',
  create_time timestamp,
  CONSTRAINT pk_survey_enterprise_group_rel PRIMARY KEY (enterprise_id, group_id)
);

COMMENT ON TABLE survey_enterprise_group_rel IS '问卷企业与分组关联';
COMMENT ON COLUMN survey_enterprise_group_rel.enterprise_id IS '企业ID';
COMMENT ON COLUMN survey_enterprise_group_rel.group_id IS '分组ID';

-- 问卷企业库菜单和按钮权限
INSERT INTO sys_menu(menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark)
SELECT 2000, '问卷调研', 0, 5, 'survey', NULL, '', '', 1, 0, 'M', '0', '0', '', 'form', 'admin', current_timestamp, '', NULL, '问卷调研目录'
WHERE NOT EXISTS (SELECT 1 FROM sys_menu WHERE menu_id = 2000);

INSERT INTO sys_menu(menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark)
SELECT 2001, '企业库管理', 2000, 1, 'enterprise', 'survey/enterprise/index', '', '', 1, 0, 'C', '0', '0', 'survey:enterprise:list', 'peoples', 'admin', current_timestamp, '', NULL, '企业库管理菜单'
WHERE NOT EXISTS (SELECT 1 FROM sys_menu WHERE menu_id = 2001);

INSERT INTO sys_menu(menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark)
SELECT 2002, '企业查询', 2001, 1, '', '', '', '', 1, 0, 'F', '0', '0', 'survey:enterprise:query', '#', 'admin', current_timestamp, '', NULL, ''
WHERE NOT EXISTS (SELECT 1 FROM sys_menu WHERE menu_id = 2002);

INSERT INTO sys_menu(menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark)
SELECT 2003, '企业新增', 2001, 2, '', '', '', '', 1, 0, 'F', '0', '0', 'survey:enterprise:add', '#', 'admin', current_timestamp, '', NULL, ''
WHERE NOT EXISTS (SELECT 1 FROM sys_menu WHERE menu_id = 2003);

INSERT INTO sys_menu(menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark)
SELECT 2004, '企业修改', 2001, 3, '', '', '', '', 1, 0, 'F', '0', '0', 'survey:enterprise:edit', '#', 'admin', current_timestamp, '', NULL, ''
WHERE NOT EXISTS (SELECT 1 FROM sys_menu WHERE menu_id = 2004);

INSERT INTO sys_menu(menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark)
SELECT 2005, '企业删除', 2001, 4, '', '', '', '', 1, 0, 'F', '0', '0', 'survey:enterprise:remove', '#', 'admin', current_timestamp, '', NULL, ''
WHERE NOT EXISTS (SELECT 1 FROM sys_menu WHERE menu_id = 2005);

INSERT INTO sys_menu(menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark)
SELECT 2006, '企业导出', 2001, 5, '', '', '', '', 1, 0, 'F', '0', '0', 'survey:enterprise:export', '#', 'admin', current_timestamp, '', NULL, ''
WHERE NOT EXISTS (SELECT 1 FROM sys_menu WHERE menu_id = 2006);

INSERT INTO sys_menu(menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark)
SELECT 2007, '企业导入', 2001, 6, '', '', '', '', 1, 0, 'F', '0', '0', 'survey:enterprise:import', '#', 'admin', current_timestamp, '', NULL, ''
WHERE NOT EXISTS (SELECT 1 FROM sys_menu WHERE menu_id = 2007);

INSERT INTO sys_menu(menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark)
SELECT 2008, '分组查询', 2001, 7, '', '', '', '', 1, 0, 'F', '0', '0', 'survey:enterprise:group:list', '#', 'admin', current_timestamp, '', NULL, ''
WHERE NOT EXISTS (SELECT 1 FROM sys_menu WHERE menu_id = 2008);

INSERT INTO sys_menu(menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark)
SELECT 2009, '分组详情', 2001, 8, '', '', '', '', 1, 0, 'F', '0', '0', 'survey:enterprise:group:query', '#', 'admin', current_timestamp, '', NULL, ''
WHERE NOT EXISTS (SELECT 1 FROM sys_menu WHERE menu_id = 2009);

INSERT INTO sys_menu(menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark)
SELECT 2010, '分组新增', 2001, 9, '', '', '', '', 1, 0, 'F', '0', '0', 'survey:enterprise:group:add', '#', 'admin', current_timestamp, '', NULL, ''
WHERE NOT EXISTS (SELECT 1 FROM sys_menu WHERE menu_id = 2010);

INSERT INTO sys_menu(menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark)
SELECT 2011, '分组修改', 2001, 10, '', '', '', '', 1, 0, 'F', '0', '0', 'survey:enterprise:group:edit', '#', 'admin', current_timestamp, '', NULL, ''
WHERE NOT EXISTS (SELECT 1 FROM sys_menu WHERE menu_id = 2011);

INSERT INTO sys_menu(menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark)
SELECT 2012, '分组删除', 2001, 11, '', '', '', '', 1, 0, 'F', '0', '0', 'survey:enterprise:group:remove', '#', 'admin', current_timestamp, '', NULL, ''
WHERE NOT EXISTS (SELECT 1 FROM sys_menu WHERE menu_id = 2012);
