-- 问卷模块 004：调研任务、抽样和模拟发卷

CREATE TABLE IF NOT EXISTS survey_task (
  task_id bigint not null GENERATED BY DEFAULT AS IDENTITY,
  task_name varchar(120) not null,
  questionnaire_id bigint not null,
  sample_source varchar(16) not null,
  sampling_method varchar(16) not null,
  sample_size int default 0,
  group_id bigint,
  token_expire_hours int default 168,
  send_channels varchar(64) default 'sms,site',
  status char(1) default '1',
  dispatch_time timestamp,
  del_flag char(1) default '0',
  create_by varchar(64) default '',
  create_time timestamp,
  update_by varchar(64) default '',
  update_time timestamp,
  remark varchar(500) default null,
  CONSTRAINT pk_survey_task PRIMARY KEY (task_id)
);

ALTER TABLE survey_task ADD COLUMN IF NOT EXISTS send_channels varchar(64) default 'sms,site';

COMMENT ON TABLE survey_task IS '调研任务';
COMMENT ON COLUMN survey_task.questionnaire_id IS '已发布问卷ID';
COMMENT ON COLUMN survey_task.sample_source IS '样本来源（all全部 group分组 enterprise指定企业）';
COMMENT ON COLUMN survey_task.sampling_method IS '抽样方式（random随机 stratified分层 specified指定）';
COMMENT ON COLUMN survey_task.send_channels IS '模拟发送渠道，逗号分隔';
COMMENT ON COLUMN survey_task.status IS '状态（0草稿 1已抽样 2已发卷 3已结束）';

CREATE TABLE IF NOT EXISTS survey_task_sample (
  sample_id bigint not null GENERATED BY DEFAULT AS IDENTITY,
  task_id bigint not null,
  enterprise_id bigint not null,
  enterprise_name varchar(120) not null,
  credit_code varchar(18) not null,
  region_name varchar(64) default '',
  industry_category varchar(64) default '',
  enterprise_scale varchar(32) default '',
  contact_phone varchar(20) default '',
  token varchar(64) not null,
  token_expire_time timestamp not null,
  qr_content varchar(500) not null,
  status char(1) default '0',
  create_time timestamp,
  CONSTRAINT pk_survey_task_sample PRIMARY KEY (sample_id),
  CONSTRAINT uk_survey_task_sample_token UNIQUE (token)
);

COMMENT ON TABLE survey_task_sample IS '调研任务样本';
COMMENT ON COLUMN survey_task_sample.token IS '公开填报token';
COMMENT ON COLUMN survey_task_sample.token_expire_time IS 'token失效时间';
COMMENT ON COLUMN survey_task_sample.qr_content IS '二维码内容';
COMMENT ON COLUMN survey_task_sample.status IS '状态（0待发送 1已发送 2已填报 3已失效）';

CREATE TABLE IF NOT EXISTS survey_task_send_record (
  record_id bigint not null GENERATED BY DEFAULT AS IDENTITY,
  task_id bigint not null,
  sample_id bigint not null,
  enterprise_id bigint not null,
  channel varchar(16) not null,
  receiver varchar(120) default '',
  content varchar(500) default '',
  send_status char(1) default '0',
  create_time timestamp,
  CONSTRAINT pk_survey_task_send_record PRIMARY KEY (record_id)
);

COMMENT ON TABLE survey_task_send_record IS '调研任务发送记录';
COMMENT ON COLUMN survey_task_send_record.channel IS '发送渠道（sms短信 site站内信）';
COMMENT ON COLUMN survey_task_send_record.send_status IS '发送状态（0已生成）';

CREATE INDEX IF NOT EXISTS idx_survey_task_questionnaire ON survey_task(questionnaire_id);
CREATE INDEX IF NOT EXISTS idx_survey_task_sample_task ON survey_task_sample(task_id);
CREATE INDEX IF NOT EXISTS idx_survey_task_sample_enterprise ON survey_task_sample(enterprise_id);
CREATE INDEX IF NOT EXISTS idx_survey_task_record_task ON survey_task_send_record(task_id);

-- 调研任务菜单和按钮权限
INSERT INTO sys_menu(menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark)
SELECT 2000, '问卷调研', 0, 5, 'survey', NULL, '', '', 1, 0, 'M', '0', '0', '', 'form', 'admin', current_timestamp, '', NULL, '问卷调研目录'
WHERE NOT EXISTS (SELECT 1 FROM sys_menu WHERE menu_id = 2000);

INSERT INTO sys_menu(menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark)
SELECT 2030, '调研任务', 2000, 3, 'task', 'survey/task/index', '', '', 1, 0, 'C', '0', '0', 'survey:task:list', 'list', 'admin', current_timestamp, '', NULL, '调研任务菜单'
WHERE NOT EXISTS (SELECT 1 FROM sys_menu WHERE menu_id = 2030);

INSERT INTO sys_menu(menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark)
SELECT 2031, '任务查询', 2030, 1, '', '', '', '', 1, 0, 'F', '0', '0', 'survey:task:query', '#', 'admin', current_timestamp, '', NULL, ''
WHERE NOT EXISTS (SELECT 1 FROM sys_menu WHERE menu_id = 2031);

INSERT INTO sys_menu(menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark)
SELECT 2032, '任务新增', 2030, 2, '', '', '', '', 1, 0, 'F', '0', '0', 'survey:task:add', '#', 'admin', current_timestamp, '', NULL, ''
WHERE NOT EXISTS (SELECT 1 FROM sys_menu WHERE menu_id = 2032);

INSERT INTO sys_menu(menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark)
SELECT 2033, '任务删除', 2030, 3, '', '', '', '', 1, 0, 'F', '0', '0', 'survey:task:remove', '#', 'admin', current_timestamp, '', NULL, ''
WHERE NOT EXISTS (SELECT 1 FROM sys_menu WHERE menu_id = 2033);

INSERT INTO sys_menu(menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark)
SELECT 2034, '任务发卷', 2030, 4, '', '', '', '', 1, 0, 'F', '0', '0', 'survey:task:dispatch', '#', 'admin', current_timestamp, '', NULL, ''
WHERE NOT EXISTS (SELECT 1 FROM sys_menu WHERE menu_id = 2034);

INSERT INTO sys_menu(menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark)
SELECT 2035, '任务列表', 2030, 5, '', '', '', '', 1, 0, 'F', '0', '0', 'survey:task:list', '#', 'admin', current_timestamp, '', NULL, ''
WHERE NOT EXISTS (SELECT 1 FROM sys_menu WHERE menu_id = 2035);
