-- 问卷模块本地 MySQL 菜单同步脚本
-- 用途：当前若依本地/Docker system 服务仍使用 MySQL 时，同步问卷后台菜单。
-- 注意：问卷业务表和演示数据仍以 sql/kingbase 下脚本为准。

SET NAMES utf8mb4;

INSERT INTO sys_menu(menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark)
VALUES
(2000, '问卷调研', 0, 5, 'survey', NULL, '', '', 1, 0, 'M', '0', '0', '', 'form', 'admin', NOW(), '', NULL, '问卷调研目录'),
(2001, '企业库管理', 2000, 1, 'enterprise', 'survey/enterprise/index', '', '', 1, 0, 'C', '0', '0', 'survey:enterprise:list', 'peoples', 'admin', NOW(), '', NULL, '企业库管理菜单'),
(2002, '企业查询', 2001, 1, '', '', '', '', 1, 0, 'F', '0', '0', 'survey:enterprise:query', '#', 'admin', NOW(), '', NULL, ''),
(2003, '企业新增', 2001, 2, '', '', '', '', 1, 0, 'F', '0', '0', 'survey:enterprise:add', '#', 'admin', NOW(), '', NULL, ''),
(2004, '企业修改', 2001, 3, '', '', '', '', 1, 0, 'F', '0', '0', 'survey:enterprise:edit', '#', 'admin', NOW(), '', NULL, ''),
(2005, '企业删除', 2001, 4, '', '', '', '', 1, 0, 'F', '0', '0', 'survey:enterprise:remove', '#', 'admin', NOW(), '', NULL, ''),
(2006, '企业导出', 2001, 5, '', '', '', '', 1, 0, 'F', '0', '0', 'survey:enterprise:export', '#', 'admin', NOW(), '', NULL, ''),
(2007, '企业导入', 2001, 6, '', '', '', '', 1, 0, 'F', '0', '0', 'survey:enterprise:import', '#', 'admin', NOW(), '', NULL, ''),
(2008, '分组查询', 2001, 7, '', '', '', '', 1, 0, 'F', '0', '0', 'survey:enterprise:group:list', '#', 'admin', NOW(), '', NULL, ''),
(2009, '分组详情', 2001, 8, '', '', '', '', 1, 0, 'F', '0', '0', 'survey:enterprise:group:query', '#', 'admin', NOW(), '', NULL, ''),
(2010, '分组新增', 2001, 9, '', '', '', '', 1, 0, 'F', '0', '0', 'survey:enterprise:group:add', '#', 'admin', NOW(), '', NULL, ''),
(2011, '分组修改', 2001, 10, '', '', '', '', 1, 0, 'F', '0', '0', 'survey:enterprise:group:edit', '#', 'admin', NOW(), '', NULL, ''),
(2012, '分组删除', 2001, 11, '', '', '', '', 1, 0, 'F', '0', '0', 'survey:enterprise:group:remove', '#', 'admin', NOW(), '', NULL, ''),
(2020, '问卷管理', 2000, 2, 'questionnaire', 'survey/questionnaire/index', '', '', 1, 0, 'C', '0', '0', 'survey:questionnaire:list', 'form', 'admin', NOW(), '', NULL, '问卷管理菜单'),
(2021, '问卷查询', 2020, 1, '', '', '', '', 1, 0, 'F', '0', '0', 'survey:questionnaire:query', '#', 'admin', NOW(), '', NULL, ''),
(2022, '问卷新增', 2020, 2, '', '', '', '', 1, 0, 'F', '0', '0', 'survey:questionnaire:add', '#', 'admin', NOW(), '', NULL, ''),
(2023, '问卷修改', 2020, 3, '', '', '', '', 1, 0, 'F', '0', '0', 'survey:questionnaire:edit', '#', 'admin', NOW(), '', NULL, ''),
(2024, '问卷删除', 2020, 4, '', '', '', '', 1, 0, 'F', '0', '0', 'survey:questionnaire:remove', '#', 'admin', NOW(), '', NULL, ''),
(2025, '问卷发布', 2020, 5, '', '', '', '', 1, 0, 'F', '0', '0', 'survey:questionnaire:publish', '#', 'admin', NOW(), '', NULL, ''),
(2026, '问卷结束', 2020, 6, '', '', '', '', 1, 0, 'F', '0', '0', 'survey:questionnaire:end', '#', 'admin', NOW(), '', NULL, ''),
(2027, '问卷列表', 2020, 7, '', '', '', '', 1, 0, 'F', '0', '0', 'survey:questionnaire:list', '#', 'admin', NOW(), '', NULL, ''),
(2030, '调研任务', 2000, 3, 'task', 'survey/task/index', '', '', 1, 0, 'C', '0', '0', 'survey:task:list', 'list', 'admin', NOW(), '', NULL, '调研任务菜单'),
(2031, '任务查询', 2030, 1, '', '', '', '', 1, 0, 'F', '0', '0', 'survey:task:query', '#', 'admin', NOW(), '', NULL, ''),
(2032, '任务新增', 2030, 2, '', '', '', '', 1, 0, 'F', '0', '0', 'survey:task:add', '#', 'admin', NOW(), '', NULL, ''),
(2033, '任务删除', 2030, 3, '', '', '', '', 1, 0, 'F', '0', '0', 'survey:task:remove', '#', 'admin', NOW(), '', NULL, ''),
(2034, '任务发卷', 2030, 4, '', '', '', '', 1, 0, 'F', '0', '0', 'survey:task:dispatch', '#', 'admin', NOW(), '', NULL, ''),
(2035, '任务列表', 2030, 5, '', '', '', '', 1, 0, 'F', '0', '0', 'survey:task:list', '#', 'admin', NOW(), '', NULL, '')
ON DUPLICATE KEY UPDATE
  menu_name = VALUES(menu_name),
  parent_id = VALUES(parent_id),
  order_num = VALUES(order_num),
  path = VALUES(path),
  component = VALUES(component),
  query = VALUES(query),
  route_name = VALUES(route_name),
  is_frame = VALUES(is_frame),
  is_cache = VALUES(is_cache),
  menu_type = VALUES(menu_type),
  visible = VALUES(visible),
  status = VALUES(status),
  perms = VALUES(perms),
  icon = VALUES(icon),
  update_by = 'admin',
  update_time = NOW(),
  remark = VALUES(remark);

-- 营商无感完整模块菜单同步。这里只写 sys_menu，本地业务表仍由 Kingbase/Postgres 脚本维护。
INSERT INTO sys_menu(menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark)
VALUES
(3000, '数据采集管理', 0, 1, 'collection', NULL, '', '', 1, 0, 'M', '0', '0', '', 'table', 'admin', NOW(), 'admin', NOW(), '数据采集管理'),
(3010, '采集任务列表', 3000, 1, 'task', 'nocontact/collection/task/index', '', '', 1, 0, 'C', '0', '0', 'nocontact:fusion:task:list', 'list', 'admin', NOW(), 'admin', NOW(), '采集任务列表'),
(3016, '新增采集任务', 3000, 2, 'create', 'nocontact/collection/create/index', '', '', 1, 0, 'C', '0', '0', 'nocontact:fusion:task:add', 'edit', 'admin', NOW(), 'admin', NOW(), '新增采集任务'),
(3030, '数据填报入口', 3000, 3, 'fill', 'nocontact/collection/fill/index', '', '', 1, 0, 'C', '0', '0', 'nocontact:fusion:collection:list', 'form', 'admin', NOW(), 'admin', NOW(), '数据填报入口'),
(3035, '数据审核中心', 3000, 4, 'audit', 'nocontact/collection/audit/index', '', '', 1, 0, 'C', '0', '0', 'nocontact:fusion:collection:audit', 'validCode', 'admin', NOW(), 'admin', NOW(), '数据审核中心'),
(3040, '采集监控看板', 3000, 5, 'monitor', 'nocontact/collection/monitor/index', '', '', 1, 0, 'C', '0', '0', 'nocontact:fusion:task:query', 'dashboard', 'admin', NOW(), 'admin', NOW(), '采集监控看板'),
(3050, '作业调度管理', 3000, 6, 'schedule', 'nocontact/collection/schedule/index', '', '', 1, 0, 'C', '0', '0', 'monitor:job:list', 'job', 'admin', NOW(), 'admin', NOW(), '作业调度管理'),
(3060, '资源目录管理', 3000, 7, 'resource', 'nocontact/collection/resource/index', '', '', 1, 0, 'C', '0', '0', 'nocontact:fusion:resource:list', 'tree', 'admin', NOW(), 'admin', NOW(), '资源目录管理'),
(3100, '指标体系管理', 0, 2, 'indicator-system', NULL, '', '', 1, 0, 'M', '0', '0', '', 'tree-table', 'admin', NOW(), 'admin', NOW(), '指标体系管理'),
(3020, '指标体系列表', 3100, 1, 'list', 'nocontact/indicator/list/index', '', '', 1, 0, 'C', '0', '0', 'nocontact:fusion:indicator:list', 'tree-table', 'admin', NOW(), 'admin', NOW(), '指标体系列表'),
(3120, '新增/编辑指标体系', 3100, 2, 'editor', 'nocontact/indicator/editor/index', '', '', 1, 0, 'C', '0', '0', 'nocontact:fusion:indicator:add', 'edit', 'admin', NOW(), 'admin', NOW(), '新增/编辑指标体系'),
(3130, '评价算法管理', 3100, 3, 'algorithm', 'nocontact/indicator/algorithm/index', '', '', 1, 0, 'C', '0', '0', 'nocontact:fusion:indicator:list', 'education', 'admin', NOW(), 'admin', NOW(), '评价算法管理'),
(3140, '标签分类管理', 3100, 4, 'tag', 'nocontact/indicator/tag/index', '', '', 1, 0, 'C', '0', '0', 'nocontact:fusion:indicator:list', 'dict', 'admin', NOW(), 'admin', NOW(), '标签分类管理'),
(3200, '检测预警中心', 0, 3, 'warning', NULL, '', '', 1, 0, 'M', '0', '0', '', 'bell', 'admin', NOW(), 'admin', NOW(), '检测预警中心'),
(3210, '预警规则列表', 3200, 1, 'rule-list', 'nocontact/warning/rule-list/index', '', '', 1, 0, 'C', '0', '0', 'nocontact:warning:rule:list', 'dict', 'admin', NOW(), 'admin', NOW(), '预警规则列表'),
(3216, '新增/编辑预警规则', 3200, 2, 'rule-editor', 'nocontact/warning/rule-editor/index', '', '', 1, 0, 'C', '0', '0', 'nocontact:warning:rule:add', 'edit', 'admin', NOW(), 'admin', NOW(), '新增/编辑预警规则'),
(3220, '预警消息管理', 3200, 3, 'message', 'nocontact/warning/message/index', '', '', 1, 0, 'C', '0', '0', 'nocontact:warning:message:list', 'message', 'admin', NOW(), 'admin', NOW(), '预警消息管理'),
(3230, '分级预警看板', 3200, 4, 'dashboard', 'nocontact/warning/dashboard/index', '', '', 1, 0, 'C', '0', '0', 'nocontact:warning:dashboard:query', 'dashboard', 'admin', NOW(), 'admin', NOW(), '分级预警看板'),
(3300, '问题整改管理', 0, 4, 'rectification', NULL, '', '', 1, 0, 'M', '0', '0', '', 'documentation', 'admin', NOW(), 'admin', NOW(), '问题整改管理'),
(3310, '问题台账列表', 3300, 1, 'issue', 'nocontact/rectification/issue/index', '', '', 1, 0, 'C', '0', '0', 'nocontact:rectification:issue:list', 'list', 'admin', NOW(), 'admin', NOW(), '问题台账列表'),
(3320, '问题详情与处理流程', 3300, 2, 'detail', 'nocontact/rectification/detail/index', '', '', 1, 0, 'C', '0', '0', 'nocontact:rectification:issue:query', 'guide', 'admin', NOW(), 'admin', NOW(), '问题详情与处理流程'),
(3330, '整改跟踪看板', 3300, 3, 'dashboard', 'nocontact/rectification/dashboard/index', '', '', 1, 0, 'C', '0', '0', 'nocontact:rectification:issue:list', 'dashboard', 'admin', NOW(), 'admin', NOW(), '整改跟踪看板'),
(2000, '问卷调研管理', 0, 5, 'survey', NULL, '', '', 1, 0, 'M', '0', '0', '', 'form', 'admin', NOW(), 'admin', NOW(), '问卷调研管理'),
(2001, '企业库管理', 2000, 1, 'enterprise', 'survey/enterprise/index', '', '', 1, 0, 'C', '0', '0', 'survey:enterprise:list', 'peoples', 'admin', NOW(), 'admin', NOW(), '企业库管理'),
(2020, '问卷管理', 2000, 2, 'questionnaire', 'survey/questionnaire/index', '', '', 1, 0, 'C', '0', '0', 'survey:questionnaire:list', 'form', 'admin', NOW(), 'admin', NOW(), '问卷管理'),
(2028, '问卷设计器', 2000, 3, 'designer', 'survey/designer/index', '', '', 1, 0, 'C', '0', '0', 'survey:questionnaire:add', 'edit', 'admin', NOW(), 'admin', NOW(), '问卷设计器'),
(2030, '样本抽取与发卷', 2000, 4, 'sample', 'survey/sample/index', '', '', 1, 0, 'C', '0', '0', 'survey:task:list', 'peoples', 'admin', NOW(), 'admin', NOW(), '样本抽取与发卷'),
(2036, '填报追踪', 2000, 5, 'tracking', 'survey/tracking/index', '', '', 1, 0, 'C', '0', '0', 'survey:task:query', 'eye-open', 'admin', NOW(), 'admin', NOW(), '填报追踪'),
(2037, '满意度统计分析', 2000, 6, 'analytics', 'survey/analytics/index', '', '', 1, 0, 'C', '0', '0', 'survey:task:query', 'chart', 'admin', NOW(), 'admin', NOW(), '满意度统计分析'),
(3400, '外部系统对接', 0, 6, 'integration', NULL, '', '', 1, 0, 'M', '0', '0', '', 'link', 'admin', NOW(), 'admin', NOW(), '外部系统对接'),
(3410, '对接配置管理', 3400, 1, 'config', 'nocontact/integration/config/index', '', '', 1, 0, 'C', '0', '0', 'nocontact:integration:config:list', 'build', 'admin', NOW(), 'admin', NOW(), '对接配置管理'),
(3420, '新增/编辑对接配置', 3400, 2, 'editor', 'nocontact/integration/editor/index', '', '', 1, 0, 'C', '0', '0', 'nocontact:integration:config:add', 'edit', 'admin', NOW(), 'admin', NOW(), '新增/编辑对接配置'),
(3430, '同步日志与监控', 3400, 3, 'log', 'nocontact/integration/log/index', '', '', 1, 0, 'C', '0', '0', 'nocontact:integration:log:list', 'log', 'admin', NOW(), 'admin', NOW(), '同步日志与监控'),
(3500, '报告自动生成', 0, 7, 'report', NULL, '', '', 1, 0, 'M', '0', '0', '', 'documentation', 'admin', NOW(), 'admin', NOW(), '报告自动生成'),
(3510, '报告模板管理', 3500, 1, 'template', 'nocontact/report/template/index', '', '', 1, 0, 'C', '0', '0', 'nocontact:report:template:list', 'form', 'admin', NOW(), 'admin', NOW(), '报告模板管理'),
(3520, '报告模板设计器', 3500, 2, 'designer', 'nocontact/report/designer/index', '', '', 1, 0, 'C', '0', '0', 'nocontact:report:template:add', 'edit', 'admin', NOW(), 'admin', NOW(), '报告模板设计器'),
(3530, '报告生成任务', 3500, 3, 'task', 'nocontact/report/task/index', '', '', 1, 0, 'C', '0', '0', 'nocontact:report:task:list', 'job', 'admin', NOW(), 'admin', NOW(), '报告生成任务')
ON DUPLICATE KEY UPDATE
  menu_name = VALUES(menu_name),
  parent_id = VALUES(parent_id),
  order_num = VALUES(order_num),
  path = VALUES(path),
  component = VALUES(component),
  query = VALUES(query),
  route_name = VALUES(route_name),
  is_frame = VALUES(is_frame),
  is_cache = VALUES(is_cache),
  menu_type = VALUES(menu_type),
  visible = VALUES(visible),
  status = VALUES(status),
  perms = VALUES(perms),
  icon = VALUES(icon),
  update_by = 'admin',
  update_time = NOW(),
  remark = VALUES(remark);

INSERT INTO sys_menu(menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark)
VALUES
(3061, '资源查询', 3060, 1, '', '', '', '', 1, 0, 'F', '0', '0', 'nocontact:fusion:resource:query', '#', 'admin', NOW(), 'admin', NOW(), ''),
(3062, '资源新增', 3060, 2, '', '', '', '', 1, 0, 'F', '0', '0', 'nocontact:fusion:resource:add', '#', 'admin', NOW(), 'admin', NOW(), ''),
(3063, '资源修改', 3060, 3, '', '', '', '', 1, 0, 'F', '0', '0', 'nocontact:fusion:resource:edit', '#', 'admin', NOW(), 'admin', NOW(), ''),
(3064, '资源删除', 3060, 4, '', '', '', '', 1, 0, 'F', '0', '0', 'nocontact:fusion:resource:remove', '#', 'admin', NOW(), 'admin', NOW(), ''),
(3311, '问题查询', 3310, 1, '', '', '', '', 1, 0, 'F', '0', '0', 'nocontact:rectification:issue:query', '#', 'admin', NOW(), 'admin', NOW(), ''),
(3312, '问题新增', 3310, 2, '', '', '', '', 1, 0, 'F', '0', '0', 'nocontact:rectification:issue:add', '#', 'admin', NOW(), 'admin', NOW(), ''),
(3313, '问题处理', 3310, 3, '', '', '', '', 1, 0, 'F', '0', '0', 'nocontact:rectification:issue:edit', '#', 'admin', NOW(), 'admin', NOW(), ''),
(3314, '问题删除', 3310, 4, '', '', '', '', 1, 0, 'F', '0', '0', 'nocontact:rectification:issue:remove', '#', 'admin', NOW(), 'admin', NOW(), ''),
(3411, '对接查询', 3410, 1, '', '', '', '', 1, 0, 'F', '0', '0', 'nocontact:integration:config:query', '#', 'admin', NOW(), 'admin', NOW(), ''),
(3412, '对接新增', 3410, 2, '', '', '', '', 1, 0, 'F', '0', '0', 'nocontact:integration:config:add', '#', 'admin', NOW(), 'admin', NOW(), ''),
(3413, '对接修改', 3410, 3, '', '', '', '', 1, 0, 'F', '0', '0', 'nocontact:integration:config:edit', '#', 'admin', NOW(), 'admin', NOW(), ''),
(3414, '对接删除', 3410, 4, '', '', '', '', 1, 0, 'F', '0', '0', 'nocontact:integration:config:remove', '#', 'admin', NOW(), 'admin', NOW(), ''),
(3431, '日志查询', 3430, 1, '', '', '', '', 1, 0, 'F', '0', '0', 'nocontact:integration:log:list', '#', 'admin', NOW(), 'admin', NOW(), ''),
(3511, '模板查询', 3510, 1, '', '', '', '', 1, 0, 'F', '0', '0', 'nocontact:report:template:query', '#', 'admin', NOW(), 'admin', NOW(), ''),
(3512, '模板新增', 3510, 2, '', '', '', '', 1, 0, 'F', '0', '0', 'nocontact:report:template:add', '#', 'admin', NOW(), 'admin', NOW(), ''),
(3513, '模板修改', 3510, 3, '', '', '', '', 1, 0, 'F', '0', '0', 'nocontact:report:template:edit', '#', 'admin', NOW(), 'admin', NOW(), ''),
(3514, '模板删除', 3510, 4, '', '', '', '', 1, 0, 'F', '0', '0', 'nocontact:report:template:remove', '#', 'admin', NOW(), 'admin', NOW(), ''),
(3531, '任务查询', 3530, 1, '', '', '', '', 1, 0, 'F', '0', '0', 'nocontact:report:task:query', '#', 'admin', NOW(), 'admin', NOW(), ''),
(3532, '任务新增', 3530, 2, '', '', '', '', 1, 0, 'F', '0', '0', 'nocontact:report:task:add', '#', 'admin', NOW(), 'admin', NOW(), ''),
(3533, '任务生成', 3530, 3, '', '', '', '', 1, 0, 'F', '0', '0', 'nocontact:report:task:edit', '#', 'admin', NOW(), 'admin', NOW(), '')
ON DUPLICATE KEY UPDATE
  menu_name = VALUES(menu_name),
  parent_id = VALUES(parent_id),
  order_num = VALUES(order_num),
  path = VALUES(path),
  component = VALUES(component),
  perms = VALUES(perms),
  update_by = 'admin',
  update_time = NOW(),
  remark = VALUES(remark);
